### ISSUE TITLE
Crash on Calculate

### ISSUE THREAD

**Issue by MortenManden** [Eduap-com/WordMat#1]
Have tried all morning to install Wordmat
- win10 64bit
- office 2016 64 bit

- Anti virus has been deactivated during install
- Porgram has been run as administrator

Wordmat is shown in Word and I can write functions but as soon as I click Calculate (Beregn) it crashes saying that Wordmat was not installed correct

**Comment by Eduap-com** [comment]
Hopefully resolved by now
