### ISSUE TITLE
Windows Defender identifying Wordmat as a trojan horse

### ISSUE THREAD

**Issue by Nuggihehe** [Eduap-com/WordMat#10]
So as my title says, wordmat got identified as a trojan horse, what should I do about this?
Here's the link to the screenshot: https://imgur.com/a/5SAU4ae

**Comment by CarlosBon** [comment]
Same issue :(
Wordmath stopped working and can't be reinstalled due to virus warning

**Comment by Eduap-com** [comment]
Microsoft was informed of the issue. It was a false positive and they have now corrected the problem
