### ISSUE TITLE
M1: Kan ikke løse differentialligning hvis videnskabelig notation er slået til.

### ISSUE THREAD

**Issue by palmer312** [Eduap-com/WordMat#103]
Prøver at løse differentialligningen:
(x+5)·y^'=√y
Gennem P(-4,1)
Kan godt løses hvis videnskabelig notation er slået fra. Hvis videnskabelig notation er slået til får jeg beskeden:
´´´
Differentialligningen kunne ikke løses
ev(scinotall(%),numer)Maxima encountered a Lisp error: The value   "5" is not of type   LISTAutomatically continuing.To enable the Lisp debugger set *debugger-hook* to nil.
´´´
På M1 Mac.

**Comment by Eduap-com** [comment]
Fejlen kan genskabes, også på Windows.
Det ser ud til at fejlen sker i scinotall.

Hvis man tager løsningen til differentialligningen: y=(ln⁡(|x+5|)+2)^2/4
og foretager alm. beregning på udtrykket (med vid not) så kommer fejlen også.

Fejlen kan også fremkaldes med beregning på  |x+5|


Her output fra Debugmode:
fejl;simplify(ConvertToDegr(desolvereal((x+5)*'diff(y,x,round(1))=sqrt(y),x=-4,y=1)));scinotall(%),numer;

(%i3) 
(%o4) fejl
expt: undefined: 0 to a negative exponent.
Assumptions:  [log(abs(x+5))+%c >= 0] 
expt: undefined: 0 to a negative exponent.
expt: undefined: 0 to a negative exponent.
(%o5) [y = (log(abs(x+5))+2)^2/4]
Maxima encountered a Lisp error:
 The value
   "5"
 is not of type
   LIST
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.

**Comment by Eduap-com** [comment]
Problemet er løst
