### ISSUE TITLE
Macro i fremtiden på Microsoft Word

### ISSUE THREAD

**Issue by IBG-IT** [Eduap-com/WordMat#104]
Er der gjort nogen tanker omkring Macro i Word, når Microsoft begrænser brugen i fremtiden ?
omtalt her:
https://admin.microsoft.com/?auth_upn=tgadm%40ikast-gym.dk&source=applauncher&ref=MessageCenter/:/messages/MC437557 
Thue

**Comment by soegaard** [comment]
Hej @IBG-IT 

Har du et andet link til nyheden?

Jeg ser:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/461765/203273366-c9a07d5a-9c0a-4289-89fb-385e029b3e3a.png">

**Comment by soegaard** [comment]
Det handler om standard-indstillingen for Office-filer hentet fra nettet.
Spørgsmålet er om WordMat's filer hører med i kategorien "fra nettet".

<img width="710" alt="image" src="https://user-images.githubusercontent.com/461765/203302876-6e2238f6-e460-4ecc-a968-452b36699c5e.png">

Den hurtigste måde at få et svar er at prøve det af.
Prøv at blokere for VBA-makroer for internettet. Tjek så om WordMat stadig virker.

**Comment by Eduap-com** [comment]
Tak for oplysningen. Jeg havde set problemet i anden sammenhæng hvor en makrofil blev hentet direkte ned, men vidste ikke hvorfor.
Jeg tror dog ikke dette kommer til at berøre WordMat, da WordMat.dotm installeres via en installer. WordMat.dotm filen er også digitalt signeret, så den burde få lov til at blive kørt.
