### ISSUE TITLE
Fejl med wordmat, 

### ISSUE THREAD

**Issue by Jotaro3TP** [Eduap-com/WordMat#107]
**Windows eller Mac**
Windows

**WordMat version**
Windows Version 1.25.2 (23/8-2022)

**Beskriv fejlen**
Antivirus gør at der ikke kan bruges maxima som engine 

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1.Klik ind til wordmat-felt 
2. Udfør en beregning  
3. Der dukker et felt op med at wordmat ikke er installeret korrekt 

**Forventet opførsel**
Burde udføre regnestykket

**Screenshots**
![josjsoj](https://user-images.githubusercontent.com/110970040/204500833-1f7c734a-223d-4b32-adb6-623a6b4add49.png)

**Comment by Eduap-com** [comment]
Kommer der efterfølgende en fejl omkring 'class not registered'?

**Comment by Eduap-com** [comment]
Ingen feedback
