### ISSUE TITLE
Makroen blev ikke fundet

### ISSUE THREAD

**Issue by HeidiGraversen** [Eduap-com/WordMat#11]
Efter genstart af min Windows PC fik jeg nedenstående fejlmeddelelse. Den forsvandt med 3 klik på "OK", men der er intet WordMat længere i Word. Hvis jeg klikker på WordMat fanen fremkommer samme meddelelse, men den lader sig ikke lukke.
WordMat er aktivt som tilføjelsesprogram, men det virker ikke.

<img width="407" alt="Udklip" src="https://user-images.githubusercontent.com/52176022/79562888-0aac0f80-80ac-11ea-8d82-46e61dbf67ad.PNG">

mvh Heidi Graversen

**Comment by Eduap-com** [comment]
I cannot solve this problem from the information given
