### ISSUE TITLE
Error calculating e^(2*ln(x))

### ISSUE THREAD

**Issue by Soeren8** [Eduap-com/WordMat#111]
Windows.
WordMat 1.25.2.

WordMat makes an error calculating e^(2*ln(x)) = e^2*ln(x).
Without the multiplication asterix WordMat calculate correct e^(2ln(x)) = x^2.

<img width="113" alt="image" src="https://user-images.githubusercontent.com/103884567/208618966-230d0e61-7244-4570-b551-b0092fd6963f.png">

**Comment by Soeren8** [comment]
<img width="205" alt="e^(2ln(x)) docx" src="https://user-images.githubusercontent.com/103884567/208620702-2a13db6e-668b-401b-85a5-61e4a3b923cc.png">

**Comment by Eduap-com** [comment]
Jeg er ikke i stand til at genskabe problemet. Kan du sende Word-dokument?

**Comment by Soeren8** [comment]
Jeg kan heller ikke genskabe problemet igen. Jeg ved ikke hvad der er sket:)
