### ISSUE TITLE
Differential

### ISSUE THREAD

**Issue by CosmicPro** [Eduap-com/WordMat#118]
![image_2023-02-24_144915003](https://user-images.githubusercontent.com/30251145/221252008-18c85b04-b494-4e88-9c72-466bd80b253a.png)
![image_2023-02-24_145021295](https://user-images.githubusercontent.com/30251145/221252194-dd5686a8-b439-4d91-af81-4f3925959229.png)
![image_2023-02-24_145059539](https://user-images.githubusercontent.com/30251145/221252320-b4c45183-cc19-4459-815f-083e1c12a0d3.png)
![image](https://user-images.githubusercontent.com/30251145/221252491-89d9b387-b315-4f22-bcd0-d74941158204.png)
Jeg prøvede at løse differentialligning, men det lykkedes ikke...
Man kan så på billeder hvad jeg gjort, den siger at det er en maxima error...
Mit WordMat er på 1.52.2, Word er på Version 2301 (Build 16026.20146), så er mit bærbar er på Windows 11, version 22H2.

**Comment by Eduap-com** [comment]
Jeg har testet med den første ligning du skriver. Den virker.
