### ISSUE TITLE
Trekanrsberegner på mac M1

### ISSUE THREAD

**Issue by GERMURBRO** [Eduap-com/WordMat#123]
**Windows eller Mac**
Hvis Mac er det så Intel eller M1
M1 
**WordMat version**
Hvilken version? 
Nyeste
**Beskriv fejlen**
Klar og præcis beskrivelse af fejlen.
Når jeg indtaster en værdi over 100 i trekantberegnerens side a, eks 104 rundes den siden ned til 100 eller andre hele hundrede. 

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Gå til '...'
2. Klik  '....'
3. Scroll ned til '....'

**Forventet opførsel**
En klar og præcis beskrivelse af hvad du forventede skulle ske

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
Send meget gerne screenshots der viser problemet.

**Comment by Eduap-com** [comment]
Jeg kan ikke genskabe problemet. Måske har antal betydende cifre været sat til 2?

**Comment by Eduap-com** [comment]
Lukkes pga manglende feedback
