### ISSUE TITLE
Fejl ved løsning af trigonometriske ligninger

### ISSUE THREAD

**Issue by Klaus-nfg** [Eduap-com/WordMat#127]
**Windows eller Mac**
Generelt på alle

**WordMat version**
sidste nye

**Beskriv fejlen**
Se vedhæftede fil.
WM angiver delvist løsninger udenfor værdimængden

**Trin til genskabelse af fejlen**
Se vedhæftede

**Forventet opførsel**
se vedhæftede

**Dokument**
Tilføj dokument der kan frembringe fejlen.
[Løsning af trigonometriske ligninger i WM - PROBLEMS.docx](https://github.com/Eduap-com/WordMat/files/11332928/Losning.af.trigonometriske.ligninger.i.WM.-.PROBLEMS.docx)

**Screenshots**
se vedhæftede

**Comment by TheBIGmag** [comment]
første gang jeg skriver noget i det her projekt... har vi nogen ide om hvilken fil der står for løsningen af ligninger?

**Comment by Eduap-com** [comment]
Problemet kræver en ændring i ligningsløseren, og det er meget arbejdskrævende proces, med risiko for at forårsage andre problemer. Den sparkes til hjørne indtil der er flere ting der skal behandles i ligningsløseren
