### ISSUE TITLE
Numeriske ligninger i Wordmat oplever funktionsfejl

### ISSUE THREAD

**Issue by BlueGDK** [Eduap-com/WordMat#128]
**Windows eller Mac**
Windows

**WordMat version**
1.25.2

**Beskriv fejlen**
Når jeg forsøger at anvende makroen "2 x Alt+m" til numerering af ligninger, oplever jeg en problematisk opførsel, hvor nummereringen ikke overholder den højrejustering, der er specificeret i indstillingerne. Dette manifesterer sig i en afvigende formatering, som vist på følgende link: [https://i.imgur.com/63DbDOs.png](https://i.imgur.com/63DbDOs.png) Det skal bemærkes, at når denne fejl først opstår, fortsætter den med at optræde indtil dokumentet lukkes og genåbnes, hvorefter nummereringen formateres korrekt, men efterfølgende igen kan afvige fra ønsket placering.

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Åbn dokumentet, hvor nummereringen skal indsættes.
2. Indsæt en numereret ligning ved hjælp af makroen "2 x Alt+m".
3. Observer, om nummereringen bliver placeret korrekt i højre side eller ej.
4. Gentag trin 2-3 for at bekræfte, at problemet vedrørende fejlagtig nummereringsplacering vedbliver med at opstå.
5. Gem dokumentet og genåbn det.
6. Indsæt en ny numereret ligning ved hjælp af makroen "2 x Alt+m".
7. Observer, om nummereringen bliver placeret korrekt i højre side eller ej.
8. Gentag trin 6-7 for at bekræfte, om problemet med nummereringsplaceringen opstår igen efter genåbning af dokumentet.

**Forventet opførsel**
Der er en forventning om, at nummereringen vil blive korrekt placeret i højre side, således at den er konsistent med andre nummereringer.

**Dokument**
[Link til word dokument fremvist i skærmbilledet](https://docs.google.com/document/d/1AB57cnDN1mxeREXXcd8p26SNvVmqVlbY/edit?usp=sharing&ouid=100847016893352705291&rtpof=true&sd=true)

**Screenshots**
[https://i.imgur.com/63DbDOs.png](https://i.imgur.com/63DbDOs.png)

**Comment by TorstenOrhoj** [comment]
Spændede ...

Hvis jeg selv laver et dokument, får jeg ikke nogen fejl, når jeg opretter flere nummererede ligninger.
Hvis jeg henter dit dokument og opretter en ny nummereret ligning i det, så viser fejlen sig ganske rigtigt ...

**Comment by Eduap-com** [comment]
Jeg kan godt genskabe fejlen nogle gange. Jeg har lavet en ændring som ser ud til at virke, men jeg kan ikke være sikker på at det virker 100%, da fejlen er lidt svær at reproducere.
