### ISSUE TITLE
Differentialligninger i WordMat

### ISSUE THREAD

**Issue by Soeren8** [Eduap-com/WordMat#129]
Jeg har vedhæftet en differentialligning som version 1.22 kan løse, men version 1.25.2 kan ikke.
[Differentialligning.docx](https://github.com/Eduap-com/WordMat/files/11554217/Differentialligning.docx)

**Comment by Eduap-com** [comment]
Fejlen skyldes samme problem som ved ligningen e^-x=2
i lambertwrule2
