### ISSUE TITLE
Residualer ved eksponentiel regression i Excel forkerte

### ISSUE THREAD

**Issue by MetteBork** [Eduap-com/WordMat#13]
Residualer og residualspredning ved excel-regression er forkerte, de bliver alt for store:
[Eksponentiel regression fejl.xlsx](https://github.com/Eduap-com/WordMat/files/4627294/Eksponentiel.regression.fejl.xlsx)

Wordmatversion: 122

**Comment by perfack** [comment]
Fejlen er (så vidt jeg kan se), at den forventede værdi beregnes som b*e^(a*x) i stedet for b*e^(k*x) eller b*a^x. Kolonne N, fanen Tabel.

**Comment by MetteBork** [comment]
Tak for svar! Ved du hvornår sådan cirka det bliver rettet;-)??
Venlig hilsen Mette Hvidberg

Fra: perfack <notifications@github.com>
Sendt: 25. maj 2020 23:46
Til: Eduap-com/WordMat <WordMat@noreply.github.com>
Cc: Mette Bork Hvidberg <MEH@horsenshfogvuc.dk>; Author <author@noreply.github.com>
Emne: Re: [Eduap-com/WordMat] Residualer ved eksponentiel regression i Excel forkerte (#13)


Fejlen er (så vidt jeg kan se), at den forventede værdi beregnes som be^(ax) i stedet for be^(kx) eller b*a^x. Kolonne N, fanen Tabel.

**Comment by johcsde** [comment]
Jeg ved det ikke endnu, vores skema virker ikke for tiden (men du kan gå ud fra at vi mødes på skolen på torsdag).

Venlig hilsen
John Ole Hasselbalch Clausen
Lærer

[http://www.sde.dk/emailSignature/logo.jpg]

________________________________


Center for Sundhed & Teknik
Syddansk Erhvervsskole Odense-Vejle
Munkebjergvej 130
5230 Odense M

Telefon:
Email:
Web:

63126854
johc@sde.dk<mailto:johc@sde.dk>
www.sde.dk<http://www.sde.dk/>

**Comment by Eduap-com** [comment]
Tak, Per, for den præcise fejlfinding. Fejlen er nu rettet i koden og kommer med næste opdatering, som nok ikke lige er på trapperne. Alternativt kan man selv hente excelfilen under Windows/Excelfiles
