### ISSUE TITLE
Beregning af median - grafisk aflæsning virker ikke

### ISSUE THREAD

**Issue by TorstenOrhoj** [Eduap-com/WordMat#131]
**Windows eller Mac**
Windows

**WordMat version**
1.25.2

**Beskriv fejlen**
Når jeg i fanen "Indstillinger" i "Statistikarket" prøver at ændre beregningsmetode for medianen til "Grafisk aflæsning", forbliver værdien for medianen den samme.

**Trin til genskabelse af fejlen**
1. Tryk på "Statistik"
2. Indtast data i fanen "Data" og Klik  'Kopier til øvrige ark'. Jeg har brugt dataene "1; 2; 3; 4; 5; 5"
3. I fanen Indstillinger vælges "Grafisk aflæsning på Trappediagram'

**Forventet opførsel**
Medianen burde nu blive beregnet til 3, svarende til en kumuleret frekvens på 50 %.

**Screenshot**
![Median_problem](https://github.com/Eduap-com/WordMat/assets/111779383/c8d76a20-84e1-4184-a3e1-cb24782547f7)
Jeg kan ikke vedhæfte dokument med makroer, så I må nøjes med screenshot. 

Torsten

**Comment by soegaard** [comment]
Jeg hæfter mig ved, at der står "Makroer deaktiveret".
Skal de ikke aktiveres før arket virker?

**Comment by TorstenOrhoj** [comment]
Jo, men selv når makroer er aktiverede virker det ikke.
Jeg kom bare til at tage screendumpet på et tidspunkt, hvor makroer var slået fra. Beklager evt. forvirring.

**Comment by Eduap-com** [comment]
Programmet foretager en ny beregning efter indstillingen bliver ændret, men når frem til samme resultat.
Det kommer an på hvordan man definerer aflæsning vha. trappediagram.

**Comment by TorstenOrhoj** [comment]
Der er bare det, at i fanen "Indstillinger" står der følgende forklarende tekst i noten;

_Grafisk aflæsning
Nedre kvartil aflæses ved 25%
Median ved 50%
Øvre kvartil ved 75%
på trappediagrammet_

Med den tekst ville jeg jo forvente at med følgende data: "1; 1; 2; 2; 3; 4; 5; 5" og valg af "grafisk aflæsning" ville kvartilsættet blive "1; 2; 4" i stedet for "1,5; 2,5; 4,5" som jeg får lige nu.

**Comment by Eduap-com** [comment]
Ja det er jeg mener med definition. Med det datasæt rammer de tre linjer vandrette linjestykker fra 25%, 50% og 75% ind i trin på trappen, og dermed er det ikke klart hvilken værdi der skal findes på x-aksen, da der er et interval. Jeg har valgt at metoden tager midtpunktet af intervallet.

**Comment by TorstenOrhoj** [comment]
... men så er der vel ikke nogen forskel på de to metoder, eller ...??

I forklaring til "Tællemetode" står der følgende i noten:
_tallene skrives i ordnet rækkefølge. Midterste tal er medianen.
Nedre kvartil er medianen af alle tal mindre end medianen. Øvre kvartil er medianen af alle tal over medianen. Hvis der er et lige antal tal er medianen midt mellem de to tal om midten._

Din forklaring lyder som om, at WordMat gør det samme ved "Grafisk aflæsning", og hvis det er tilfældet er der jo ikke nogen grund til at skilte med to forskellige metoder.

Alternativt kunne jeg da godt tænke mig at se et datasæt, hvor der faktisk er forskel på de to metoder.

**Comment by Eduap-com** [comment]
Her er et eksempel, der giver to forskellige resultater med de to metoder:
1,1,1,2,2,2,2,3,3
