### ISSUE TITLE
Vektorligning - symbolet "eller" bruges i stedet for "og"

### ISSUE THREAD

**Issue by TorstenOrhoj** [Eduap-com/WordMat#135]
**Windows eller Mac**
Windows 11

**WordMat version**
1.25.2

**Beskriv fejlen**
Ved løsning af en vektorligning med to ubekendte benyttes symbolet "Eller" ved angivelse af løsning, hvor jeg ville forvente symbolet "Og". 

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Definer de tre vektorer og angiv ligningen.
2. ALT+L - angiv variabel der skal løses for (jeg kan kun angive én)
3. Tryk OK

**Forventet opførsel**
Jeg havde en forventning om, at løsningen vil blive vist med tegnet "Og" som det gøres i den tilsvarende udregning med to ligninger med to ubekendte.

**Dokument**
[WordMat_fejl_vektorligning.docx](https://github.com/Eduap-com/WordMat/files/12343839/WordMat_fejl_vektorligning.docx)

**Screenshots**
![Fejl_Vektorligning](https://github.com/Eduap-com/WordMat/assets/111779383/e777d73a-b5a5-47af-a5d5-90bffe3c8681)

**Comment by TorstenOrhoj** [comment]
Jeg opdagede lige, at version 1.26. er udkommet, og her sker det samme.

**Comment by Eduap-com** [comment]
Problemet skulle være løst
