### ISSUE TITLE
Beregning af simpelt udtryk med Maxima giver uhensigtsmæssigt resultat

### ISSUE THREAD

**Issue by mathiasfugmann** [Eduap-com/WordMat#145]
Beregning af 1*3,6+1,2*(-3) giver ikke nul, men 4,440892*10^-16, uanset eksakt/numerisk indstilling ved brug af Maxima som CAS-motor. Ved brug af GeoGebra som CAS-motor giver det eksakt 0.

Testet på macOS 13.5.2 med WordMat 1.26.1.

**Comment by Eduap-com** [comment]
Det skyldes en intern repræsentation af binære-tal i CAS-programmet. 
Tal der ser eksakte ud i 10-talssystemer bliver i virkeligheden ikke repræsenteret eksakt binært.
