### ISSUE TITLE
"Der skete en fejl i forsøget på at starte maxia ErrCode: 2"

### ISSUE THREAD

**Issue by MadsMMP** [Eduap-com/WordMat#147]
**Windows eller Mac**
Lenovo T14 GEN 2

**WordMat version**
1.26

**Beskriv fejlen**
Ved beregning af ligning siger den, "Der skete en fejl i forsøget på at starte maxia ErrCode: 2"

**Trin til genskabelse af fejlen**
1. Opret et Dokument
2. Lav en ligning med ALT+M
3. Tryk ALT+B for at beregne og så sker det.

**Forventet opførsel**
Den løser ligningen

**Screenshots**
![fejl](https://github.com/Eduap-com/WordMat/assets/54959437/b456cd45-5cfa-4273-b0f9-e5431f150251)

**Comment by Eduap-com** [comment]
Det er en fejl der er relateret til den bestemte maskine. 
Jeg er desværre ikke i stand til at tilbyde gratis support til programmet. Der er mange tusind brugere, og jeg modtager derfor rigtigt mange henvendelser.
Din skole kan vælge at indgå et WordMat partnerskab og på den måde få adgang til support.Det kan du læse mere om her: [WordMat partnerskab](https://www.eduap.com/da/partnerskab/)

Der er følgende muligheder for selv at løse problemer:

1. På WordMat's hjemmeside er der en FAQ, hvor de mest gængse problemer er beskrevet. Den opdateres løbende.
[WordMat-FAQ](https://www.eduap.com/da/wordmat-faq/)

2. På WordMat's YouTube site er der video'er der kan hjælpe. Der er bla. videoer, der beskriver mange af problemerne beskrevet i FAQ'en mere detaljeret.https://www.youtube.com/playlist?list=PLBE92A91925446259

3. På WordMat's GitHub side under discussions kan du oprette et indlæg og spørge efter hjælp. Her svarer jeg nogle gange, men det kan også være at andre kan hjælpe. Det kan også være, at du kan finde et indlæg som handler om dit problem. https://github.com/Eduap-com/WordMat/discussions

4. På WordMat's Facebook side omtales også jævnligt problemer og der kan i nogle tilfælde være hjælp at hentehttps://www.facebook.com/wordmat
