### ISSUE TITLE
Freeze when calculating derivative (parsing error?)

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#15]
Here is a file that can cause wordmat to freeze if I press ctrl-B the wrong place.

[freeze_when_calculating_derivative.docx](https://github.com/Eduap-com/WordMat/files/4667478/freeze_when_calculating_derivative.docx)

If I press ctrl-B in an equation containing a derivative f'(x) then word will sometimes rewrite the equation to place '(x) in the exponent. This can lead to an equation that wordmat cannot parse.

**Comment by Eduap-com** [comment]
Jeg kan ikke genskabe problemet. Det kan skyldes særlige indstillinger, men formentligt at problemet er løst via senere opdatering af enten Word eller WordMat
