### ISSUE TITLE
Wordmat virker ikke efter har opdateret Macbook til Sonoma 14.0

### ISSUE THREAD

**Issue by KenLabrosse** [Eduap-com/WordMat#151]
**Windows eller Mac**
M1

**WordMat version**
Mac-M1/2 Version 1.26.1

**Beskriv fejlen**
Når noget skal beregnes, så vil den hverken beregne eller solve

<img width="1066" alt="image" src="https://github.com/Eduap-com/WordMat/assets/145003535/f8101264-ad09-4cbb-8b29-7f64c213922d">

**Comment by livschmidt3** [comment]
Jeg har samme problem..

**Comment by livschmidt3** [comment]
Jeg har samme problem..

**Comment by Eduap-com** [comment]
Maxima virker ikke med Sonoma. Brug GeoGebra som CAS-motor, indtil der kommer en ny version
