### ISSUE TITLE
Syntax Error.

### ISSUE THREAD

**Issue by MikkelYT10** [Eduap-com/WordMat#152]
Windows

1.26

Om det er 1 + 2 eller to kvadratroder, divideret med hindanden, så sker det samme som på billedet.

1. Lav en ligning ALT + m
2. Skriv ligningen på billedet 
3. Tryk beregn ALT + B

Forventede at få svaret af lignigen.

*Jeg har et helveds langt dokument med dagsopgaver for vektore, som bliver brugt i undervisningen (36+ sider)

![image](https://github.com/Eduap-com/WordMat/assets/73175061/4cbacbc0-d62e-4bbe-be66-c55ba51af9e6)
![image](https://github.com/Eduap-com/WordMat/assets/73175061/a379eb41-87c8-4b93-bb71-09c61c5a5339)

**Comment by Eduap-com** [comment]
Problemet kan ikke genskabes. 
Det kan skyldes den måde det er tastet på (Send dokument, i stedet for screenshot)
Men kan også være en bestem indstilling, eller noget andet i dokumentet

**Comment by Eduap-com** [comment]
Sagen lukkes pga manglende feedback.
