### ISSUE TITLE
Wordmat giver ingen respons.

### ISSUE THREAD

**Issue by MikkelYT10** [Eduap-com/WordMat#154]
Windows

1.27

1. Ingen af genvejene virker, såsom ALT + B
2. Trykkes der beregn, så ligner det den prøver, men fejler og giver ingen feedback.
3. På en anden Laptop kan jeg udregne 1+1, men når det bliver kompliceret så crasher det.

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Åben filen
2. Prøv at trykke ALT + m for ny ligning eller 1+1 i en ligning og udregn ved hjælp af ALT+B
3. Se at der ingen forbindelse er til wordmat, og at man selv ikke hvis der trykkes "Beregn" kan få et svar

**Forventet opførsel**
Håbede på at få løst ligningen

**Dokument**
Tilføj dokument der kan frembringe fejlen. 
[Hjemmeopgave - Skulptur.docx](https://github.com/Eduap-com/WordMat/files/13074307/Hjemmeopgave.-.Skulptur.docx)

**Comment by Eduap-com** [comment]
Problemet kan ikke genskabes. Det vil kræve undersøgelse af den konkrete computer.
https://www.eduap.com/da/partnerskab/
