### ISSUE TITLE
Wordmat beregner ikke.

### ISSUE THREAD

**Issue by MikkelYT10** [Eduap-com/WordMat#155]
Windows

1.27

Wordmat kan ikke beregne overhovedet

1. Skriv f.eks, 1+1 eller a=1+1 og brug hendoldsvis ALT+B / beregn eller ALT+L for at finde a

Der sker intet, den tager lige i et kort sekund og ser ud som om den udregner det, men ingen resultat, og ved a=1+1 sker følgende i screenshottet.

[WordmatAintWorkin.docx](https://github.com/Eduap-com/WordMat/files/13167739/WordmatAintWorkin.docx)

![image](https://github.com/Eduap-com/WordMat/assets/73175061/db0e281e-9c45-442a-b2f1-c745a1425c0c)

Udover det så få jeg en "Der skete en fejl" ( På min laptop. IKKE samme enhed som jeg får ovenfor's fejl på) uanset hvad jeg prøver at beregne, men bliver der lidt mere kompliceret, som f.eks differential regning, så crasher word bare.

**Comment by Eduap-com** [comment]
Det er et problem på denne computer, som nok kræver support.
