### ISSUE TITLE
Wordmat vil ikke beregne på Mac M1

### ISSUE THREAD

**Issue by famenglund** [Eduap-com/WordMat#156]
Mac M1/2?

**WordMat version**
Nyeste version 

**Beskriv fejlen**
Efter Mac update vil wordmat ikke beregne. Den giver fejlmeddelelsen "Afbrudt" - Kommandoen blev afbrudt efter 5s. Vil du prøve igen og hvor lang tid vil du vente (sekunder) Computeren låses i ventetiden.

Vi har forsøgt at downloade nyeste version wordmat og gå tilbage til ældre versioner med samme fejl.

**Trin til genskabelse af fejlen**
Så snart man trykker på "beregne" eller bruger genvejstasten kommer fejlen.

**Forventet opførsel**
Jeg forventede at wordmat regnede stykket som den plejer.

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

*Screenshots**
Send meget gerne screenshots der viser problemet.

![image](https://github.com/Eduap-com/WordMat/assets/149473280/0199bed7-7fd1-4d62-aa26-298957cccfb4)

**Comment by Ke-rem** [comment]
WordMat virker ikke på Sonoma.

**Comment by briank73** [comment]
Efter at have fulgt ovenstående virker wordmat næsten - vi kan nu ikke få tastaturgenveje til at virke. Nogen ideer?

**Comment by briank73** [comment]
Tak for super hurtigt svar - men vi har selv fundet løsningen, som var at gå ind i wordmats indstillinger og under avanceret at genetablere genveje.
