### ISSUE TITLE
WM vil ikke give et eksakt resultat

### ISSUE THREAD

**Issue by Leine57** [Eduap-com/WordMat#157]
**Windows eller Mac**
Windows 10

**WordMat version**
1.27 

**Beskriv fejlen**
WM vil ikke levere et eksakt resultat, selvom skærmbilledet undervejs viser, at resultatet ER regnet ud.
Se vedhæftede fil

**Trin til genskabelse af fejlen**
Se filen

**Forventet opførsel**
WM skal give et eksakt svar, når det er muligt.

**Dokument**
Se vedhæftede 

**Screenshots**
Se i dokumentet
[231031 WordMat problem.docx](https://github.com/Eduap-com/WordMat/files/13215860/231031.WordMat.problem.docx)

**Comment by soegaard** [comment]
Skærmbillede af ovenstående:

<img width="562" alt="image" src="https://github.com/Eduap-com/WordMat/assets/461765/a03ea554-980a-41dc-bcb3-863668bac0a3">

**Comment by Eduap-com** [comment]
løst
