### ISSUE TITLE
(Mac) Antallet af betydende cifre forbliver uændret, uanset indstillinger.

### ISSUE THREAD

**Issue by C1ariea** [Eduap-com/WordMat#169]
**Windows eller Mac**
Mac, 13 stk, Op til Sonoma

**WordMat version**
Op til Version 1.28-1

**Beskriv fejlen**
Når man forsøger at ændre antallet af betydende cifre, fx til 4, forbliver antallet betydende cifre i outputtet uændret. 

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Gå til Wordmat-båndet
2. Ændre antallet af betydene cifre
3. Lave regnestykke fx 10/3

Alternativt.
1.Gå til Wordmat-båndet
2. Åben indstillinger 
3. Ændre antallet af betydene cifre
4. Lave regnestykke fx 10/3

**Forventet opførsel**
Når man får resultatet, så er der kun 3 cifre efter kommaet, hvis betydende cifre er sat til 3.

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
Send meget gerne screenshots der viser problemet.

**Comment by Eduap-com** [comment]
Løst
