### ISSUE TITLE
Solving equations of the form x = expression

### ISSUE THREAD

**Issue by soegaard** [Eduap-com/WordMat#17]
Given an equation of the form 
      x = expression
where x is free in expression, students ought to click "evaluate",
but often they (to much chagrin of the teacher) click "solve equation".

Since it is easy to determine whether an expression is free of the variable
to solve for, I suggest that solving such an equation automatically
switches to "evaluate" (or perhaps prompts the student).

Example:

Solving  `x=1+2` currently leads to  this output:

    x=1+2 
            solved by Wordmat
    x=2

I suggest the following output instead:

    x=1+2 ~ 3

**Comment by Eduap-com** [comment]
Jeg er ikke helt enig.
Jeg synes det viser noget om elevens forståelse af sit CAS-værktøj om de kan vælge den rigtige funktion. Hvis de beder om at få løst en ligning, så er det det som skal gøres også selvom den allerede er løst.
De elever der vælger 'forkert' får stadig løst opgaven. De elever som vælger mere hensigtsmæssigt har mulighed for at vise en lidt dybere forståelse.
