### ISSUE TITLE
Løs ligning virker ikke på mac

### ISSUE THREAD

**Issue by Magn109d** [Eduap-com/WordMat#178]
**Windows eller Mac**
Hvis Mac er det så Intel eller M1/2?
M2

**WordMat version**
Hvilken version? 
1.26

**Beskriv fejlen**
Klar og præcis beskrivelse af fejlen.
Hver gang jeg siger til wordmat, den enten skal løse en ligning, eller regne simple regnestykker ud, kommer den op med en denne fejlmeddelse "Kommandoen blev afbrudt efter 5s, vil du prøve igen, og hvor lang tid vil du vente. Computeren låses i mellem tiden" hvis jeg så siger ok, kommer den samme besked op igen

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Gå til 'Hvilket som helst problem, og bed wordmat om og løse det, jeg bruger option+b'
2. Klik  '....'
3. Scroll ned til '....'

**Forventet opførsel**
En klar og præcis beskrivelse af hvad du forventede skulle ske
Den ville regne regnestykket ud
**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
Send meget gerne screenshots der viser problemet.

<img width="1657" alt="Screenshot 2024-01-23 at 11 12 43" src="https://github.com/Eduap-com/WordMat/assets/157479362/c5355197-eec8-4861-83c1-2f0c9a815913">

**Comment by Eduap-com** [comment]
Du kører en ældre version. Dette er et problem på din computer, som nok kræver support.
