### ISSUE TITLE
Reduction error: 1/3(-2)^3 = (-2/3)^3

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#18]
Here is an example where wordmat interprets 1/3(-2)^3 as (-2/3)^3, but the student meant to write 1/3*(-2)^3

[fejl med potens.docx](https://github.com/Eduap-com/WordMat/files/4727332/fejl.med.potens.docx)

**Comment by Eduap-com** [comment]
Der kan opstå mange problemer, når eleven indtaster uden at tage hensyn til de skjulte parenteser. Der bliver gjort en del i koden for at tage højde for det, men i nogle tilfælde er de skjulte parenteser nødvendige.
Dette problem er nu løst, men der vil formentlig være flere tilfælde, der skal løses. Måske der kunne laves en validering, så man fik at vide, at der muligvis er et fortolkningsproblem.
