### ISSUE TITLE
Dialogboks halvt ude af skærmen ved afslutning af Word

### ISSUE THREAD

**Issue by mathiasfugmann** [Eduap-com/WordMat#180]
**Windows eller Mac**
Mac M1, Sonoma 14.1.2

**WordMat version**
1.28

**Beskriv fejlen**
Hvis WordMat har været brugt og Word så skal afsluttes med cmd+Q, kommer en dialogboks frem om hvorvidt man vil gemme det dokument, WordMat bruger i baggrunden til udregninger. Dialogboksen dukker dog op så langt nede i det ene hjørne af skærmen, at man ikke kan vælge knapperne i dialogboksen. Der er så ingen andre udveje end at afbryde Word (cmd+option+esc).

**Trin til genskabelse af fejlen**
1. Udfør en beregning med WordMat.
2. Afslut Word med cmd+Q.

**Forventet opførsel**
Jeg forventer at dialogboksens knapper til "Slet", "Annuller" og "Gem" er synlige i skærmbilledet.

**Dokument**
Opret et dokument og regn f.eks. 2+2 med alt+B.

**Screenshots**
<img width="1028" alt="Skærmbillede 2024-01-29 kl  09 47 00" src="https://github.com/Eduap-com/WordMat/assets/93997454/e5aa8e44-5441-4644-9bd9-a61375586fa9">

**Comment by Eduap-com** [comment]
Der fundet en løsning, der også grundlæggende skulle løse andre problemer med det skjulte dokument
