### ISSUE TITLE
Forkert partielle afledede

### ISSUE THREAD

**Issue by DomenicaToro** [Eduap-com/WordMat#195]
**Windows 

**WordMat version**1.29 (9/2-2024) ~180MB

**Beskriv fejlen**
Jeg kan ikke beregn den rigtig partielle afledede

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Skrive funktion med to variable
2. Skrive blood d til at beregn partielle aflede mht. x
3. Alt+B

**Forventet opførsel**
Jeg forventer at det beregne partielle afledede for  hele funktion og ikke kun den foorste dele, men det manglar 2y

**Dokument**
[fjel med partielle afledede.docx](https://github.com/Eduap-com/WordMat/files/14409344/fjel.med.partielle.afledede.docx)

![image](https://github.com/Eduap-com/WordMat/assets/161366688/e4413329-fa59-4195-ab83-43313b57f173)

**Screenshots**
Send meget gerne screenshots der viser problemet.

Tak for hjaelpen!

**Comment by Eduap-com** [comment]
Problemet skyldes forkert input.
