### ISSUE TITLE
gemmefejl

### ISSUE THREAD

**Issue by nebsen123** [Eduap-com/WordMat#199]
**Windows eller Mac**
Windows
**WordMat version**
1.29
**Beskriv fejlen**
Hvis man insætter et citat lige efter et matematikfelt, kan man ikke gemme dokumentet.
**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Lav et matematikfelt og skriv noget i det.
2. tilføj et citat
3. indsæt citatet
4. prøv at gem dokumentet

**Forventet opførsel**
Man burde kunne gemme, eller der burde være en advarsel om, at det man gør, er det der er grunden til, at man ikke kan gemme dokumentet.
**Dokument**
virker selvfølgelig ikke.
**Screenshots**
Send meget gerne screenshots der viser problemet.
2. ![image](https://github.com/Eduap-com/WordMat/assets/39364278/5d050cc8-fb77-46ca-b52a-7fbb195d2f2b)
3. ![image](https://github.com/Eduap-com/WordMat/assets/39364278/cb7dc577-5940-44ca-a82a-23cbec24ea3c)
4. ![image](https://github.com/Eduap-com/WordMat/assets/39364278/6cef59b0-fd24-42eb-900e-871a07ce1590)

**Comment by Eduap-com** [comment]
Dette anvender ikke nogen funktioner i WordMat. Matematikfelter er indbygget i Word, så det skal nok fejlmeldes til Microsoft.
