### ISSUE TITLE
Beregning af konfidensinterval fejl

### ISSUE THREAD

**Issue by perfack** [Eduap-com/WordMat#20]
Beregning af konfidensinterval i binomialtest.xlsx er ikke korrekt.
Funktionerne binomlow og binomhigh anvender forventet p-værdi til beregning af antal successer.
Det bør være observeret p-værdi, således at antal successer bliver et helt tal.
Alternativ skal antal successer indtastes, og observeret p-værdi beregnes.

Altså i celle J20:
- binomlow(C2*C3; ...
rettes til
- binomlow(C2*C4; ...

Tilsvarende for binomhigh.

**Comment by Eduap-com** [comment]
Burde være løst nu.
