### ISSUE TITLE
Minimum afhænger af intervallerne

### ISSUE THREAD

**Issue by Leine57** [Eduap-com/WordMat#200]
**Windows eller Mac**
Windows 11

**WordMat version**
1.29

**Beskriv fejlen**
Mine elever har arbejdet med dine statistikfiler i Excel. Her dukkede et problem op.
Som du kan se i den vedhæftede fil, så har de indtastet 32 observationer, hvor den mindste er  på 3407.
Hvis jeg lader intervallerne starte i 3400, bliver denne mindsteværdi også overført til de næste faneblade, som jeg ville forvente.
Men nogle elever har - som i filen - valgt at lade intervallerne starte ved 3000. Og selvom der er registreret 0 observationer i det første interval, så bliver 3000 alligevel registreret som minimum, når data bliver overført.

**Trin til genskabelse af fejlen**
Se herover
[240305 Øvelse 259 til Mikael.zip](https://github.com/Eduap-com/WordMat/files/14569866/240305.Ovelse.259.til.Mikael.zip)

**Forventet opførsel**
At minimum bestemmes korrekt

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
Send meget gerne screenshots der viser problemet.

**Comment by Eduap-com** [comment]
Løst for ugrupperet og grupperet
