### ISSUE TITLE
Udregning, hvor punktum og komma indgår.

### ISSUE THREAD

**Issue by froksen** [Eduap-com/WordMat#202]
**Windows eller Mac**
Windows 10

**WordMat version**
1.25.2

**Beskriv fejlen**
Oplever med mine grundskoleelever, at hvis eleverne ønsker at benytte tusindedele punktum i regnestykker samtidigt andre tal med decimalkomma at det giver udfordringer. 
Dette sker selvom der via indstillinger er opsat, at komma er decimaldeler.

Eksempel herunder
![image](https://github.com/Eduap-com/WordMat/assets/1126216/285364b5-2479-4bc7-8dd3-f617a46a8a1c)

**Ønsket/forslag til opførsel**
Naturligvis letteste måde at løse er, at bede eleverne om ikke at bruge tusindedele punktum. Men ville det være muligt, at lave en "messagebox alarm" hvor der fremgår, udfordringen og/eller, at man kan tvinge programmet til ikke at acceptere regnestykker hvor begge notationer indgår? Dette kunne ske i indstillinger, således folk der ønsker den anden oplevelse fortsat kan dette. 

**Dokument**
[Doc med eksempel.docx](https://github.com/Eduap-com/WordMat/files/14600741/Doc.med.eksempel.docx)

**Screenshots**
![image](https://github.com/Eduap-com/WordMat/assets/1126216/579c390a-1a27-4fb8-90ca-2a09d6aeab1a)

**Comment by Eduap-com** [comment]
Det bliver ikke nemt at håndtere. punktum og komma kan bruges som decimalseparator og listeseparator fx
[2.3 , 4.5]
Det vil i så fald også komme ud som en fejl.
Der er ikke plads til tusindtalsseparatorer.

**Comment by froksen** [comment]
Hej 

Tak for godt svar, og det giver god mening at "løsning" af ovenstående blot skaber problemer andre steder :)
