### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by kaolinx** [Eduap-com/WordMat#205]
Hej, er stødt på et problem med når man skal udregne bestemte ligninger og ved ikke lige hvad jeg skal gøre længere. Har prøvet at genstarte, geninstallere og prøver at skifte mellem de forskellige indstilling.
![Fejl](https://github.com/Eduap-com/WordMat/assets/72488701/92eae1b5-3815-4dc0-b4ed-d375bc1ece21)

**Comment by Eduap-com** [comment]
Det er nok noget der kræver support. Se eduap.com under partnerskab.
