### ISSUE TITLE
Libreoffice support

### ISSUE THREAD

**Issue by coffandro** [Eduap-com/WordMat#206]
Heya, I would just like to request that this might possibly be ported to Linux so that it, for example, could be used by the 4%(almost 6 in Denmark!) of users who use Linux or so that it can later be ported to ChromeOS with libreoffice easier.
I might add it myself in a PR but that would probably take a while, I'm a student, so I just wanted to see if there was something against it before I began.

**Comment by soegaard** [comment]
@coffandro  WordMat is a plugin for Microsoft Word. This implies, that Microsoft needs to make a Linux version first.

If you want to use Microsoft Word (the Windows version) on Linux, look into installing it in a virtual machine.

**Comment by coffandro** [comment]
Yeah true then I guess I'm asking if it could possibly be ported to Libreoffice since it seems to be able to open word plugins without a problem

**Comment by soegaard** [comment]
LibreOffice / OpenOffice works differently under the hood, so it is not a simple task to make a version for LibreOffice.

But components used by WordMat can be used on Linux.

The underlying CAS is called Maxima. You can get wxMaxima and use it directly.
Then take screenshots and paste them into LibreOffice.

https://wxmaxima-developers.github.io/wxmaxima/screenshots.html

**Comment by Eduap-com** [comment]
It's not gonna happen. It would be a completely new project built from scratch.
Please go ahead.

**Comment by coffandro** [comment]
alright
