### ISSUE TITLE
Ved silent install bliver v29 ikke ordentligt installeret

### ISSUE THREAD

**Issue by InterceptorDK** [Eduap-com/WordMat#213]
**Windows eller Mac**
Windows 11, Office 365

**WordMat version**
1.29 og 1.29.1

**Beskriv fejlen**
Ved silent install fra remote værktøj bliver den ikke ordenligt installeret.
V27 som vi kører nu virker fint. men ruller jeg 29 ud så fjerner den 27, men derefter mangler der ting. der er intet i Word. og kører du de scripts fra startmenu eller lommeregner fra der, er filerne der ikke.
Hvis du håndinstallerer ser det ud som om det virker.
Brugere er ikke local admins

**Comment by Eduap-com** [comment]
Det er nok et problem der kræver support.

**Comment by InterceptorDK** [comment]
Jeg ved ikke hvad du mener? det er en bug i softwaren, intet andet. Det har virket i alle versioner indtil 29. Jeg kan se IT Troels har lavet en post også med præcis samme problem.
