### ISSUE TITLE
Silent install / System context : Failed to expand shell folder constant "userdocs"

### ISSUE THREAD

**Issue by ITRSOELM** [Eduap-com/WordMat#214]
Når jeg forsøger at installere programmet fra system context med følgende installations Parameter: 
WordMat1291.exe /SP /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /COMPONENTS=geogebra,graph /TASKS=installeralle /LOG=C:\temp\Install.log

Før jeg følgende fejl: 
2024-04-29 13:49:54.448   Warning: SHGetFolderPath failed with code 0x80070002 on folder 0x8005
2024-04-29 13:49:54.448   Exception message:
2024-04-29 13:49:54.448   Defaulting to OK for suppressed message box (OK):
                          Intern fejl: Failed to expand shell folder constant "userdocs"
2024-04-29 13:49:54.448   Deinitializing Setup.
2024-04-29 13:49:54.453   Log closed.

Kører jeg installationen igen, så fortsætter den uden problemer. 

For at reproducere fejlen, skal de ske på en ren maskine og med PSEXEC for at kører i system context.

**Comment by InterceptorDK** [comment]
Nu for vi af se om de gider fikse det, min sag med helt det samme problem blev bare lukket.

**Comment by Eduap-com** [comment]
Dette problem kræver support. se mere her: https://www.eduap.com/da/partnerskab/
