### ISSUE TITLE
Crasher når man starter beregning

### ISSUE THREAD

**Issue by Andreas-Bugge** [Eduap-com/WordMat#215]
**Windows eller Mac**
Windows

**WordMat version**
1.29.1

**Beskriv fejlen**
Hvis jeg laver et matematisk felt med "alt+m".
og indputter hvad som helst, kan være "1+1".
hvis jeg så prøver at få det beregnet med "alt+b".
så crasher hele word dokumentet.

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. lave et matematisk felt med "alt+m".
2. indputter hvad som helst, kan være "1+1".
3. få det beregnet med "alt+b".

**Forventet opførsel**
at det ikke crasher og udrenger det til 2.

**kommentar**
Det har tidligere virket, men fra den ene dag til den anden stoppede det med at virke.
Har prøvet at downloade wordmat igen, men samme problem forkommer.

**Screenshots**
Send meget gerne screenshots der viser problemet.
![image](https://github.com/Eduap-com/WordMat/assets/114669556/23c19bd5-742a-43a7-b4d5-c5fda76871a2)

**Comment by Eduap-com** [comment]
Det er ikke generelt issue, men et problem på din computer. Det vil kræve support.
