### ISSUE TITLE
Potensproblem

### ISSUE THREAD

**Issue by Eduap-com** [Eduap-com/WordMat#216]
10^8^2 bliver fortolket som 10^64
Det burde være 10^16

**Comment by Matselvstuderende** [comment]
8^2=64
8*2=16

**Comment by soegaard** [comment]
Fra NSpire:

<img width="216" alt="image" src="https://github.com/Eduap-com/WordMat/assets/461765/d66add9f-fed3-4dd8-8bff-c9d471e75dca">

**Comment by Eduap-com** [comment]
Tak Jens. Jeg lukker den.

**Comment by Eduap-com** [comment]
Hmm interessant. Det er ikke helt veldefineret og kan behandles forskelligt i forskellige programmer.
I MatLab giver 10^8^2=10^16

De fleste benytter dog 10^64, så ingen grund til ændring.

![image](https://github.com/Eduap-com/WordMat/assets/27739684/dfda142c-86d9-44a8-9911-f19fe6c532a8)
