### ISSUE TITLE
WordMat 1.26 reagerer ikke på tastaturgenveje

### ISSUE THREAD

**Issue by Sunhealer** [Eduap-com/WordMat#219]
**Windows eller Mac**
Windows 10, Version 22H2

**WordMat version**
1.26, hentet direkte fra GitHub Releases

**Beskriv fejlen**
Tastaturgenveje fra WordMat virker ikke. Funktionerne som tastaturgenvejene burde kalde, virker når man trykker på deres respektive knapper i WordMat fanen på båndet, men ikke når man bruger tastaturgenvejene.

**Trin til genskabelse af fejlen**
1. Åbn et vilkårligt Word dokument.
2. Brug tastaturgenvejen ALT+M for at oprette en ligning.
3. En ligning bliver ikke oprettet.

**Forventet opførsel**
ALT+M burde oprette en ligning, og ALT+B burde beregne den markerede ligning.

**Allerede forsøgte løsninger**
- Reinstallering af Office 365
- Reinstallering af WordMat
- Installering af WordMat 1.29
- Installering af Office LTSC 2021

Alle forsøgte løsninger endte med at fejlen fortsatte på præcis samme måde.

**Comment by Eduap-com** [comment]
Det er et problem på din computer.
