### ISSUE TITLE
Forbedringsforslag: Unicode vs Latex

### ISSUE THREAD

**Issue by soegaard** [Eduap-com/WordMat#222]
Der er to indstillinger for formelfelterne: Unicode og Latex.

<img width="222" alt="image" src="https://github.com/Eduap-com/WordMat/assets/461765/11052c61-a8e0-4271-bb5d-fe6315348306">

Er det muligt for WordMat at tjekke jævnligt om den for WordMat korrekte indstilling er i brug?
Og komme med en besked, der forklarer at der skal skiftes tilbage.

Det lader til, at der er en tastekombination, der skifter fra den ene til den anden indstilling.
Der er derfor elever, som uden at vide det får skiftet indstillingen.

**Comment by Eduap-com** [comment]
Det er desværre ikke muligt at se eller påvirke den indstilling fra koden.
I version 1.29 blev der indført et forsøg på at identificere indstillingen, når der skete en fejl ud fra teksten.
I så fald vil man få en vejledning i hvordan man slår indstillingen fra.
