### ISSUE TITLE
Fejl ved konfidensinterval når n * p ikke giver heltal

### ISSUE THREAD

**Issue by JoasHaunstrup** [Eduap-com/WordMat#23]
I excel-arket med binominalfordeling under fanen Binominaltest giver konfidensintervallet ved nogle n og p værdier resultatet "#VÆRDI!".  Når man viser beregningstrin, kan man se at det kommer af _"Error: Numerator Not A Whole Number"_ ved beregningen "C2 * C3", altså n * p, inde i både binomlow og binomhigh. Ved at ændre "C3 * C2" til "AFRUND(C3 * C2; 0)" kommer der et konfidensinterval ved alle værdier af p og n. I sagens natur er det konfidensinterval, man får med denne modificering, dog en smule forkert, når n * p ikke giver et heltal.

Jeg tænker, at den optimale løsning ville være en ændring i binomlow og binomhigh, så de også kan arbejde med decimaltal. Jeg ved ikke hvor vanskelig den ændring er, men hvis det er for svært eller tidskrævende, tænker jeg, at man kan tilføje en afrunding, så der altid returneres et konfidensinterval, selvom det ikke er helt præcist. 

Hvis det er brugbart er det i Windows 10 i WordMat 1.22.

**Comment by perfack** [comment]
Samme som #20.  👍

**Comment by Eduap-com** [comment]
Problemet er løst i 1.24
