### ISSUE TITLE
Version 1.30 til Windows lader til at være inficeret med virus.

### ISSUE THREAD

**Issue by Richard-H-Lund** [Eduap-com/WordMat#235]
BitDefender blokkerer download med følgende meddelelse:

We blocked this dangerous page for your protection:
https://objects.githubusercontent.com/github-production-release-asset-2e65be/88663180/a7a2c301-2500-4f6e-9e4b-095540b17097?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240828%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240828T190055Z&X-Amz-Expires=300&X-Amz-Signature=f69b590509427c8bdaefe3070b80eccf3cd692f09f86c98e127293c708f94b07&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=88663180&response-content-disposition=attachment%3B%20filename%3DWordMat1291.exe&response-content-type=application%2Foctet-stream
Threat name: Trojan.GenericKD.73883362
Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.

Er dette et kendt problem eller en reel sikkerhedsbrist?

**Comment by Eduap-com** [comment]
Det er en falsk-positiv. Se FAQ
