### ISSUE TITLE
Fejlmeddelelse ved beregning integral

### ISSUE THREAD

**Issue by Vilfred422** [Eduap-com/WordMat#238]
Windows 10 Home, Wordmat version 1.30, Word version 2408 (Build 17928.20114)

Et eksempel på problemet:

Indtaster denne streng i ny ligning:
\int_0^3"mellemrum"x^2"mellemrum"\dd"mellemrum"x
Dette producerer ligningen:
∫_0^3▒〖x^2 ⅆx〗
Ved beregning får jeg følgende fejlmeddelelse:
![image](https://github.com/user-attachments/assets/d4f4c569-3e91-4bd8-ac8e-bdce47a2ad17)
og herefter denne maxima fejlmeddelelse:
![image](https://github.com/user-attachments/assets/12326e89-fb7f-40ba-a3a9-b4fb51c0c3ef)
Problemet sker på tværs af alle dokumenter.

**Comment by Eduap-com** [comment]
løst
