### ISSUE TITLE
WordMat vil ikke give den eksakte løsning

### ISSUE THREAD

**Issue by clkaa** [Eduap-com/WordMat#240]
Windows 11, WordMat version v. 1.30

WordMat vil ikke give den eksakte løsning selvom den eksakte løsning er valgt. Det samme sker, hvis den automatiske løsning er valgt. 
Ved sinus og cosinus, er problemet kun fremtrædende ved sin(pi) og cos(1/2*pi). Og desuden andre værdier af x, som giver = 0.
Desuden er 1+sin(pi) ≈ 1, selvom det burde være =1.
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ce12d4e5-6ede-4bc2-a8d9-a21900940caa">

**Comment by Eduap-com** [comment]
Problemet kan ikke genskabes. 
Det skyldes formentlig forhold på den pågældene computer.
