### ISSUE TITLE
Fil-indhold slettes. Og beregning fejler.

### ISSUE THREAD

**Issue by perfack** [Eduap-com/WordMat#244]
**Windows**
**WordMat version** 1.31
**Beskriv fejlen**
To problemer:
- Beregning af et integral fejler med Maxima.
- Fil-indhold slettes ved beregning.

**Trin til genskabelse af fejlen**
Test med filen Modul 0 v 2.docx
Se video:  [https://somup.com/cZ6XXgH0Nz](https://somup.com/cZ6XXgH0Nz)
Timestamps i video:
0:12
- Åbner filen modul 0 v2.docx
- Beregning af integral med Maxima => dokument indhold slettes.       :-(

0:28 - 
- Åbne fil igen og skifter til GeoGebra CAS
- Beregning af integral, og dokument indhold slettes igen.      :-(

0:49 
- Åbne fil igen.
- Beregne 2+2. Succes.
- Beregning af integral med GeoGebra lykkes. Succes.        :-)

1:10 
- Åbne fil igen, og skift til Maxima.
- Beregne 2+2. Success.
- Beregning af integral med Maxima, forkert svar, men dokument slettes ikke.   :-(

[Modul 0 v2.docx](https://github.com/user-attachments/files/17342180/Modul.0.v2.docx)

**Comment by Soeren8** [comment]
Hvis jeg sletter L= foran integralet, så beregner WordMat integralet. Men det er selvfølgelig ikke godt nok.

**Comment by Eduap-com** [comment]
Problemet skulle nu være løst i version 1.31.2

Problemet med sletningen af indholdet må skyldes en fejl i Word. Man kan godt se indholdet ved at skifte til kladdevisning.
Problemet er forsøgt omgået, så må giden vise om det virker for alle udtryk.
