### ISSUE TITLE
Betydende cifre i regneark (grupperede observationer)

### ISSUE THREAD

**Issue by perfack** [Eduap-com/WordMat#25]
Regneark med databehandling af grupperede observationer bør have flere betydende cifre i Frekvens og Kum.frekv. (kolonne D og E), samt felterne Observation og Fraktil (celler F9:G10).
Resultater bør som udgangspunkt ikke være uden decimaler. Afrunding bør ske af brugeren.

**Comment by Eduap-com** [comment]
Excel runder af efter hvor meget plads der er i kolonnen. 
Den var tidligere snævret meget ind pga. lave skærmopløsninger, da WordMat blev udviklet.
Den er nu udvidet.
