### ISSUE TITLE
Syntaksfejl i ligning

### ISSUE THREAD

**Issue by Davs-00** [Eduap-com/WordMat#257]
**Windows eller Mac**
Windows 11

**WordMat version**
1.31.3

**Beskriv fejlen**
Ligningen der i tidligere versioner kunne løses med resultatet 1, giver nu fejmeddelelsen: Syntaksfejl - operatoren må ikke placeres i starten af udtrykket.

**Trin til genskabelse af fejlen**
Skriv ligningen som vist i screenshot

**Forventet opførsel**
Resultatet 1, som Wordmat ver 1.30.x og 1.29.x viser.

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
![fejl](https://github.com/user-attachments/assets/877e5253-db27-454f-96ac-ee63e211162d)
![ligning](https://github.com/user-attachments/assets/c5a62334-ddf2-412f-b12c-20e453a3c359)

**Comment by perfack** [comment]
#264

**Comment by Eduap-com** [comment]
Løst
