### ISSUE TITLE
Faktorisering af tal

### ISSUE THREAD

**Issue by perfack** [Eduap-com/WordMat#26]
Faktorisering af polynomier virker fint, men faktorisering af tal virker ikke.
Menu:  Omskriv -> Faktoriser.

**Comment by nielsle** [comment]
Der virker for mig :-)
[faktorisering af tal.docx](https://github.com/Eduap-com/WordMat/files/5428902/faktorisering.af.tal.docx)

PS: Jeg tror at det er bedst at uploade en wordfil hver gang man rapporterer en fejl. Så  har programmøren lettere ved at genskabe fejlen.

**Comment by nielsle** [comment]
Rettelse. Det virker kun når man vælger "automatic" (Altså E) i wordmat-menuen
[faktorisering af tal.docx](https://github.com/Eduap-com/WordMat/files/5428967/faktorisering.af.tal.docx)

**Comment by perfack** [comment]
Jeg kan ikke få det til at virke, med automatic eller exact.
Se vedhæftede (m software versioner)
[Factor.docx](https://github.com/Eduap-com/WordMat/files/5444624/Factor.docx)

**Comment by perfack** [comment]
Nu virker det igen. WordMat versionen er uændret, men MS Word er skiftet til version 2019 MSO (16.0.10373.20050) 64-bit. Og så huske at indstille til Exact, som nævnt overnfor.
