### ISSUE TITLE
Virus ? hvorfor er version 1.31.3 fjernet fra download ?

### ISSUE THREAD

**Issue by UffeJakobsen** [Eduap-com/WordMat#265]
Windows Defender bliver ved med identificere `STARTUP/WordMat.dotm` som indeholdende `Trojan:Script/wacatac.H!ml`

Jeg kører version 1.31.3 (windows) - den version er så pludselig fjernet fra jeres download ??? nu er 1.31.2 nyeste version ???

og ingen forklaring på hvorfor den er fjernet ?

Spørgsmål: 

- har i fået "tryllet" en virus ind i version 1.31.3 ?
- skal vi blive ved med at køre 1.31.3 - eller skal vi skifte ned til "nyeste" 1.31.2 ?

Udfra issue #247  og issue #263 - så er der også problemer med både 1.31 og 1.31.2 - så det kunne være rart med noget konkret information så vi ved hvad vi har med at gøre her.

På forhånd tak

**Comment by Eduap-com** [comment]
Check FAQ. Det er falsk positiv

**Comment by UffeJakobsen** [comment]
Tak for svar

Det besvarer dog ikke spørgsmålet om hvorfor 1.31.3 pludselig ikke er til download mere...

Så os der har en lokal downloadet kopi af 1.31.3 - skal/bør vi i stedet køre 1.31.2 som nu er nyeste version ?

**Comment by Eduap-com** [comment]
Jeg kan ikke se at 1.31.3 ikke har været tilgængelig. Der har aldrig været en 1.31.3 til Mac. Måske er det problemet?.
Under alle omstændigheder er der nu en ny version.
