### ISSUE TITLE
Udregning af ligning

### ISSUE THREAD

**Issue by Kianhdoyle** [Eduap-com/WordMat#268]
**Windows eller Mac**
Hvis Mac er det så Intel eller M1/2?
M2

**WordMat version**
Hvilken version? 
Nyeste

**Beskriv fejlen**
Klar og præcis beskrivelse af fejlen.
Når jeg udregner en ligning får jeg det korrekte svar, men hvis jeg nu prøver at udregne samme ligning igen forsvinder alt i dokumentet, og der bliver bare hvidt. Der er ingen markør og man kan ikke gå tilbage. 

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Gå til '...'
2. Klik  '....'
3. Scroll ned til '....'

**Forventet opførsel**
En klar og præcis beskrivelse af hvad du forventede skulle ske

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
Send meget gerne screenshots der viser problemet.

**Comment by Kianhdoyle** [comment]
Ingen kommentar?

**Comment by Eduap-com** [comment]
Jeg kan ikke se der står noget i beskrivelsen andet end skabelonen. troede det var en fejl

**Comment by soegaard** [comment]
>> Jeg kan ikke se der står noget i beskrivelsen andet end skabelonen. troede det var en fejl

> Når jeg udregner en ligning får jeg det korrekte svar, men hvis jeg nu prøver at udregne samme ligning igen forsvinder alt i dokumentet, og der bliver bare hvidt. Der er ingen markør og man kan ikke gå tilbage.

@Kianhdoyle Jeg tror, der skal flere detaljer med, hvis Mikael skal have en chance for at gennemskue, hvad der går galt. Som minimum: versionsnumre af Word og af WordMat. Meget gerne en video, som demonstrerer problemet. 

Har du problemet ved alle ligninger - eller kun en bestemt?
Har du også problemer med udtryk?
