### ISSUE TITLE
Ligning bliver ikke udregnet til korrekt resultat

### ISSUE THREAD

**Issue by kamillehein** [Eduap-com/WordMat#27]
Jeg hjælper en elev, hvis MacBook (med Catalina) ikke vil udregne resultatet korrekt.
Vi har både tjekket i Maple 2020 og med mit eget WordMat, og ved de to bliver den udregnet korrekt.

Kender nogen en løsning? Geninstallation af Office og WordMat er forsøgt.

Jeg er vedhæftet hendes gemte dokument med ligningen i. 

[ligning.docx](https://github.com/Eduap-com/WordMat/files/5465005/ligning.docx)

**Comment by nielsle** [comment]
Hvilket resultat får I? Jeg får det samme resultat i Wordmat og Maple
![image](https://user-images.githubusercontent.com/292118/97729558-21a7d180-1ad3-11eb-8f48-a73fa51cd691.png)

**Comment by kamillehein** [comment]
Hun fik cirka 1,71.
Det blev fikset ved at skifte fra LaTex til Unicode. Ups 🤦‍♀️
