### ISSUE TITLE
Wordmat glemmer parentes omkring nævner i brøk

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#28]
Her er et dokument hvor wordmat svarer at
![image](https://user-images.githubusercontent.com/292118/99621697-dc6b2580-2a28-11eb-80e2-3dad44227e98.png)

[glemmer_parentes_omkring_nævner.docx](https://github.com/Eduap-com/WordMat/files/5564380/glemmer_parentes_omkring_naevner.docx)

Jeg tror problemet skyldes at jeg skrev med farver i matematikfeltet

**Comment by Eduap-com** [comment]
Ligningsformatet er blevet ændret på en mærkelig måde, så det ikke oversættes rigtig af Word. 
Jeg har prøvet at taste en ligning normalt og ændre farverne som i eksemplet, men der opstår problemet ikke. Jeg ved  simpelthen ikke hvordan det er blevet tastet på denne måde. Måske har Microsoft rettet problemet. Det vil formentlig ikke kunne løses via WordMat.
