### ISSUE TITLE
Gray box appears when calculating in fullscreen on Mac

### ISSUE THREAD

**Issue by McNiels100** [Eduap-com/WordMat#3]
When your are working in fullscreen on Mac (green button top-left corner), and then calculate a gray box appears in the middle of the screen. It goes away if you leave fullscreen mode (green button top-left corner). It can be seen below, but be aware it's a little hard to spot on the screenshot...

<img width="1280" alt="screenshot 2019-02-22 at 10 49 53" src="https://user-images.githubusercontent.com/39567847/53234675-5e7dbd00-3690-11e9-8efb-026760624422.png">

**Comment by Eduap-com** [comment]
Solved
