### ISSUE TITLE
Differentiation of a non defined function causes word to crash

### ISSUE THREAD

**Issue by oliverslott** [Eduap-com/WordMat#30]
Example: typing `f'(2)` and pressing alt+b when f is not defined, causes word to crash.

Wordmat version: 1.22
Platform: Windows 10 2004
[Wordmat crash.docx](https://github.com/Eduap-com/WordMat/files/5651140/Wordmat.crash.docx)

**Comment by Eduap-com** [comment]
Fejlen er nu rettet. Der vil komme en fejlmeddelse.
