### ISSUE TITLE
Bestemt integral

### ISSUE THREAD

**Issue by TiBui1504** [Eduap-com/WordMat#31]
Wordmat har et problem med at udregne bestemte integraler hvor den nedre grænse er skrevet som en potens. Der opstår en fejl i programmet når man prøver at skrive
`\int^{y^2}_{y^3} 1 dx`
Men den kan fint udregne integralet hvis man i stedet skriver
`\int^{y^2}_{y*y*y} 1 dx`
Selv noget simpelt som
`\int^{3}_{2^2} 1 dx`
kan den heller ikke udregne, men den kan sagtens udregne det hvis man skriver 2*2 i stedet for

**Comment by nielsle** [comment]
Her er en wordfil med test-cases
[integraler_med_potenser.docx](https://github.com/Eduap-com/WordMat/files/5717858/integraler_med_potenser.docx)

**Comment by Eduap-com** [comment]
Problemet er løst. Kommer med i næste version.
