### ISSUE TITLE
Fed skrift i matematikfelter giver problemer

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#32]
Hvis man skriver ligningen  2000=3000*0.85^x i et matematikfelt og laver skriften om til fed, så har wordmat problemer med at løse den.

[løse liginger med fed skrift.docx](https://github.com/Eduap-com/WordMat/files/5769196/lose.liginger.med.fed.skrift.docx)

**Comment by Eduap-com** [comment]
Der er et indbygget problem i Words ligningseditor der giver forskellige problemer, når ligninger skrives med fed.
Derfor starter WordMat med at fjerne den fede skrift. Det var ikke tilstrækkeligt i dette tilfælde.
Der er nu implementeret en ny metode til at omgå problemet, som heller ikke ændrer den eksisterende fede skrift i dokumentet.
