### ISSUE TITLE
Makro problem

### ISSUE THREAD

**Issue by CHP1234** [Eduap-com/WordMat#33]
Hej, jeg oplever at mit wordmat ikke virker og Word giver mig beskeden på billedet herunder. 

![image](https://user-images.githubusercontent.com/77393556/104455631-df594100-55a7-11eb-94d8-2a56c782d35c.png)

Efter beskeden er poppet op og lukket 3 gange, kommer jeg ind på word, hvor at wordmat så ikke virker.  Trykker man på wordmat folderen bliver man spammet med samme besked, som man skal nedkæmpe for at kunne bruge word.
Selvom man sænker sikkerhedsniveuat til alle makroer har adgang, virker det stadig ikke. Eller hvis man geninstallere wordmat og word, hjælper det heller ikke. 
Det har virket on and off længe, og opført sig efter hvilken word fil man har åbnet, men nu nægter det at samarbejde.

Er der andre der oplever det samme, og er der en løsning på dette?

**Comment by soegaard** [comment]
Har du et skærmbillede af dine makroindstillinger?

**Comment by CHP1234** [comment]
![image](https://user-images.githubusercontent.com/77393556/104458697-fac64b00-55ab-11eb-8a45-ec3b278f8e5b.png)

**Comment by soegaard** [comment]
Pas. Jeg gætter på, at Mikael vil være glad for at få versionnummeret på både Word og Wordmat oplyst,
for at have en chance for at kunne reproducere fejlen.

**Comment by CHP1234** [comment]
Word version:
![image](https://user-images.githubusercontent.com/77393556/104460146-fe5ad180-55ad-11eb-9a2e-45095b83d6f2.png)

Wordmat windows version: 1.22  (7/3-2020)

**Comment by LasseK1** [comment]
Det sjovt jeg har præcis det samme problem også med at nedkæmpe det første pop up vindue 3 gange.
Jeg får dog denne error code når jeg lukker dokumentet.
![Capture](https://user-images.githubusercontent.com/78917741/107652222-40903500-6c78-11eb-8865-ef46063e9a6c.PNG)

ellers køre jeg på word version:
![Capture1](https://user-images.githubusercontent.com/78917741/107652575-a41a6280-6c78-11eb-9a43-a755f98bc932.PNG)
 og wordmat Version 1.22 (7/3-2020)

Tænkte jeg lige ville smide det med også så der er flere systemer ind over :)

**Comment by Eduap-com** [comment]
Der er ikke så meget jeg kan gøre uden at være ved maskinen.
