### ISSUE TITLE
Fejl i løsning af trig. ligning

### ISSUE THREAD

**Issue by SoerenKS** [Eduap-com/WordMat#34]
Faldt over vedlagte problem i forbindelse med cos-relationen.
[wordmat bug.docx](https://github.com/Eduap-com/WordMat/files/5835017/wordmat.bug.docx)

**Comment by Eduap-com** [comment]
Problemet er ikke lige til at løse. Det er relateret til et problem i ligningsløseren eller maxima generelt. Resultatet der kommer ud fra maxima har en imaginær del, og derfor fejlen.
Denne ligning giver fejlen med følgende indstillinger: Maxima, eksakt, grader, kun 1 løsning
-1/2=√(98-98·cos⁡(50) )·cos⁡(A)

Med GeoGebra som CAS-motor virker det

**Comment by Eduap-com** [comment]
uddybende:
AllTrig:false$Solve((-1)/(2)=sqrt(98-98*cos(%pi/180*(50)))*cos(%pi/180*(A)),A);
   [A = (180*acos(%i/(7*2^(3/2)*sqrt(cos((5*%pi)/18)-1))))/%pi]
%,numer;
   [A = 85.15231248478261]
   
Der er %i i output, men som forsvinder ved numer.

**Comment by Eduap-com** [comment]
Problemet er nu løst ved at udføre applyconverttoreal(solq), to gange både før og efter simplifysol, der kan introducere %i
