### ISSUE TITLE
Fejl under konvertering til Tex eller PDF

### ISSUE THREAD

**Issue by jhcerdas** [Eduap-com/WordMat#35]
Når jeg forsøger at konvertere til disse formater, det siger, at jeg ikke har MikTex installeret, når jeg rent faktisk gør. Er der nogen anden måde at konvertere det? Eller hvad skal jeg gøre?
Tak

**Comment by nielsle** [comment]
Hvis du vil gemme som pdf, så kan du vælge filer -> eksporter -> pdf

Jeg har ikke checket efter om wordmat kan installere miktex automatisk. Ellers kan du finde det her 
https://miktex.org/howto/install-miktex

**Comment by jhcerdas** [comment]
Tak, fordi du svarede
Jeg mener jeg ønsker at få Tex fra min fil, og at gøre det jeg skal bruge MikTex, men det altid fortæller mig, at jeg ikke har det
Er der nogen anden måde at få Tex?
Og om PDF, foretrækker jeg ikke at bruge den, der har Word, fordi nogle gange nogle symboler forsvinder
Tak

**Comment by nielsle** [comment]
Jeg er ikke ekspert på emnet, men man kan installere miktex her.  Det er værd at prøve
https://miktex.org/howto/install-miktex

**Comment by soegaard** [comment]
Hvis MikTeX driller er en anden mulighed at bruge TeXLive. 

Men ... så vidt jeg har forstået kan WordMat ikke eksportere et dokument som TeX-fil.
Er det ikke bare et "stylesheet" til Word, som gør at fonte, overskrifter med mere
ligner Latex-dokumenter til forveksling?

**Comment by soegaard** [comment]
Mere info her:

http://wordmat.blogspot.com/2014/09/from-version-1.html

**Comment by Eduap-com** [comment]
Den funktion er i beta og langt fra færdig. Forvent der går lang tid.

**Comment by Eduap-com** [comment]
Løst, men funktionen er stadig i beta.
