### ISSUE TITLE
Eksponentiel regression i excel giver forkerte residualer

### ISSUE THREAD

**Issue by rcley** [Eduap-com/WordMat#36]
WordMat version 1.22
PC  
![image](https://user-images.githubusercontent.com/78534938/106874226-a0656980-66d5-11eb-8f6b-aa5cee5835a3.png)

Residualer og residualplot ved eksponentiel regression er meget forkerte.

[Residualproblem.docx](https://github.com/Eduap-com/WordMat/files/5924683/Residualproblem.docx)

[WordMat problem.xlsx](https://github.com/Eduap-com/WordMat/files/5924721/WordMat.problem.xlsx)
(kan ikke uploade med aktiveret makroer?)

![excel regression](https://user-images.githubusercontent.com/78534938/106875667-377ef100-66d7-11eb-9112-8a381bed26c2.jpg)

BH Richard

**Comment by nielsle** [comment]
Så vidt jeg kan se er fejlen allerede blevet rapporteret, men den rettede version er ikke udkommet endnu

https://github.com/Eduap-com/WordMat/issues/13

**Comment by Eduap-com** [comment]
Residualerne er rigtige i min test. Muligvis er det rettet før, men det kan jeg ikke huske. 
R^2 afviger dog. Det skyldes forskellige beregningsmetoder, hvor Excels formentlig beregnes på baggrund af en log-transformation. Jeg tror ikke man kan sige den ene eller den anden er mere rigtig.
Kommer med i næste version
