### ISSUE TITLE
Binomialtest

### ISSUE THREAD

**Issue by perfack** [Eduap-com/WordMat#37]
Konklusionen i binomialtest regnearket er "_0-hypotese bekræftet. Det kan ikke afvises at den observerede middelværdi: 79 er korrekt_." Det er vel ikke en middelværdi, man observeret, ej heller kan den være forkert eller korrekt.
Tegnet "my" anvendes som symbol for den observerede værdi. Det er heller ikke standard notation.

**Comment by Eduap-com** [comment]
Binomialfordelingsarket er nu rettet til.
