### ISSUE TITLE
WordMat not working on Mac M1 architecture 

### ISSUE THREAD

**Issue by JohnnyDamtoft** [Eduap-com/WordMat#39]
I've tried with 4 different Office 365 installations. Tried with version 16.43(20110804), 16.44(20121301), 16.45(21011103) and also 16.46(21021202) - and it seems all software versions are not accepting WordMat.

WordMat is reporting "error" during calculations, and after several error messages, WordMat is aborting. 

I'm using the latest Mac M1 architecture as MacBook Pro M1 and Mac Mini M1, both with the same result, which may not have support for WordMat. 

When do you have the next version of WordMat available? 
Does this version have support for M1?

**Comment by soegaard** [comment]
Hej Johnny,

Der står følgende i FAQ'en (langt nede):
![image](https://user-images.githubusercontent.com/461765/110292327-5251c780-7fed-11eb-941a-a3d8e22d0c38.png)
Mere ved jeg ikke.

**Comment by rud-holmgren** [comment]
Does anyone know what the (technical) problem is with running it on the M1?

I can help with porting if there is some kind of viable path for doing it.

**Comment by BrylleDK** [comment]
No idea what the actual technical problem is, but seems like it's something to do with the integration or functionality of maxima.  Whether it's simple multiplication or an equation I try to solve I get "Maxima Execute Error". 

But like it says the interactive excel sheets are working just fine and, to my surprise, the Triangle-solver works great as well. 

My programming's at a very basic level, so I've got no idea where to look and what to for...  but noticed in my snooping around that the Maxima-version in wordmat 1.22 is an older version 5.38 (from 2016, current being v.5.44 from 2020). Don't know if that has anything to do with it.

**Comment by nielsle** [comment]
As far as I have understood wordmat uses maxima which is written in lisp, and some of the lisp compilers did not compile  on the M1-chips. 

But I am not an expert on this, so I may be wrong

**Comment by BrylleDK** [comment]
> As far as I have understood wordmat uses maxima which is written in lisp, and some of the lisp compilers did not compile on the M1-chips.

Pardon if this question is stupid, but; If it's the compiler that seems to be the problem, would a possible solution then be to use a different compiler? (From what I've found there're some lisp-compilers that do work on the M1)

**Comment by rud-holmgren** [comment]
The recommended compiler for maxima is SBCL:

https://sourceforge.net/p/sbcl/sbcl/ci/master/tree/

And from the looks of it there are recent commits named "Darwin arm64 support":

https://sourceforge.net/p/sbcl/sbcl/ci/master/tree/src/assembly/arm64/

So maybe it is close?

**Comment by soegaard** [comment]
Hej Brylle,

Det er nok Mikael, du får det mest præcise svar fra.

Udover at have adgang til en mac med M1 er der to potentielle problemer:

1. Få Maxima op at køre på en M1. 
2. Undersøge om integrationen i Word fungerer som sædvanligt.

ad 1)
Problemet her var, at open source Common Lisp-oversætterne ikke have support fra M1 (arm64).
Det kommer stille of roligt efter som udviklerne af f.eks. SBCL får adgang til M1-maskiner.
Dernæst skal Maxima-folkene så have afprøvet om alting virker.

Det vil helt sikkert være en hjælp, hvis du afprøvede om det er muligt at få Maxima op at køre nu.
Som andre skriver, så er der sket fremskridt på oversætter-fronten de sidste par måneder.

Mailing listen for Maxima er her - og det nævnes, at SBCL har macOS/arm64 support:
https://sourceforge.net/p/maxima/mailman/message/37231117/

Der er dog endnu ingen, der har skrevet, at de har fået Maxima op at køre på en M1.


ad 2)
Hvis Maxima ellers fungerer, så skal det undersøges om Word-plugins fungerer på samme måde.
Det er ikke usandsynligt, at der er sket ændringer - men der er ikke andet for end at prøve det.

**Comment by nielsle** [comment]
Her er en anden relevant bug report
https://sourceforge.net/p/maxima/bugs/3766/?limit=100

**Comment by BrylleDK** [comment]
Chipper ind med anden relevant tråd: 
https://sourceforge.net/p/maxima/mailman/message/37286970/

SBCL understøtter nu Darwin ARM64 (/M1). Som jeg læser tråden, burde det være rimelig straight forward at compile Maxima til arm64, og jeg ville rigtig gerne gøre forsøget, men har ingen anelse om hvordan jeg lige griber det an. Har ingen erfaring med hverken compilers og CommonLisp. (Har ikke haft held til at finde noget der kunne guide mig til det)

Kan I måske guide mig i retning af noget?

**Comment by rud-holmgren** [comment]
Jeg har haft SBCL til at køre på M1'eren - men noget i interface mellem Word og SBCL knækker også. Har kigget lidt på koden, tror der er en vej igennem, men det er ikke helt simpelt desværre.

Endte med at skifte datterens Macbook ud med en Windows-laptop - det hjalp 😄 (geogebra virker heller ikke 100% på M1 — der slap tålmodigheden op)

**Comment by BrylleDK** [comment]
>  (geogebra virker heller ikke 100% på M1 — der slap tålmodigheden op)
Eneste issue jeg oplever med GeoGebra på M1 er at man ALDRIG skal gå native fullscreen, så crasher den så der kommer en popup boks.

> Jeg har haft SBCL til at køre på M1'eren - men noget i interface mellem Word og SBCL knækker også. Har kigget lidt på koden, tror der er en vej igennem, men det er ikke helt simpelt desværre.

Dejligt at der er lys for enden af tunnelen 😊
Opklarende spørgsmål, når du lykkedes med SBCL, var det så stadig maxima 5.38? Altså at du ikke ændrede noget på Wordmat 1.22?  Beklager hvis det er et irrelevant eller tåbeligt spørgsmål, er lidt på dybt vand, men vil rigtig gerne give det et forsøg også. 😅

**Comment by Nigma1337** [comment]
> Jeg har haft SBCL til at køre på M1'eren - men noget i interface mellem Word og SBCL knækker også. Har kigget lidt på koden, tror der er en vej igennem, men det er ikke helt simpelt desværre.

SBCL bruges vel kun til at compilere Maxima, right? Så den skal ikke have et interface med word. Recompilede du maxima, og prøvede der? (prikker bare lidt rundt, for at se hvor jeg skulle starte)

Surt med geogebra.

**Comment by aleksanderbl29** [comment]
M1-bruger her - Jeg kan bidrage med og fortælle at jeg har fået wxMaxima til at fungere på min M1 MacBook Pro. wxMaxima, der er GUI der kan køres sammen med Maxima. Den kører native. Installerede ved hjælp af homebrew (M1-udgave også). Jeg må gå ud fra at jeg kan grave mig frem til Maxima-delen, der laver beregningerne, der givetvis også må virke med M1. Vil gerne stille min tid og mit hardware til rådighed for test.

Jeg er kommet så langt som at have fundet det Terminal-program, der starter Maxima i CLI-form. Jeg har forsøgt at lægge den ind og justere koden for at shippe wordmat med denne, men det har ikke udbedret fejlen, der kommer når man regner (som nævnt tidligere i tråden). Det er med overvejende sandsynlighed noget i interfacet mellem Maxima og Word, hvor jeg ikke har formået at rette til, da der nok er sket ændringer med den udgave af Maxima jeg sidder med.
Er åben for forslag :)

**Comment by renelaerke** [comment]
Dejligt at se der sker lidt fremdrift :-) 

> Er åben for forslag :)

Mit ukvalificerede bud vil være at der skal kigges på MaximaConnectionDylib for at det kommer til at spille. Det skal nok som minimum compiles til M1 og lægges ind - og "måske" er der elementer i interfacet der skal justeres for at det virker. 

Selv om jeg selv er udvikler har jeg absolut ingen viden/erfaring på dette område - men jeg har downloaded Xcode på min M1 og åbner lige projektet af ren nysgerrighed. Hvis jeg er heldig (som at vinde i lotto) skal der sættes 2 flueben og compiles fra Xcode for at få en M1 version....

**Comment by rud-holmgren** [comment]
Det kan ikke gøre det med 2 flueben desværre. Jeg har bygget MaximaConnectionDylib til M1 og egentlig fået lidt liv i det. Det fungerer på den måde, at maxima startes i en separat process som MaximaConnectionDylib kommunikerer med gennem stdin/stdout. Det sker i MaximaFunctions.c:

https://github.com/Eduap-com/WordMat/blob/master/Mac/MaximaConnectionDylib/MaximaConnection/MaximaFunctions.c

Det er også ret tydeligt at forfatteren har haft en del bøvl med at få det til at køre på intel mac (der er en masse unused og udkommenteret kode). Desuden laver macos noget dylib caching som gør, at man ikke altid kører den kode man tror man kører når man sidder og udvikler på det - vær opmærksom på det :-)

I mit setup kom jeg så langt som at få maxima-processen startet, parset velkomst-beskeden fra maxima, og sende et math-expression fra word til maxima - hvorefter maxima-processen tiltede og døde. Close but no cigar...

**Comment by soegaard** [comment]
Det lyder godt nok som om, du er tæt på at have fundet en løsning.

Har du selv compilet Maxima? 

Det er ikke usandsynligt, at den Maxima, der følger med WordMat er konfigureret
en anelse anderledes end normalt. 

Betyder "tiltede og døde" betyder, at Maxima-processen kører med 100% cpu,
eller bare at der ikke kommer en besked tilbage? Hvis det sidste er tilfældet,
så kan det skyldes at læsedelen på Maxima-siden af en eller anden grund
ikke tror, at beskeden fra Word-siden er sendt færdig. 

Det er noget bøvl at debugge den slags. Har du mulighed for dels at få
Word-delen til at printe det, den sender dels at få Maxima til at printe det,
den modtager?

/Jens Axel
(som desværre ikke har en M1-maskine endnu)

**Comment by rud-holmgren** [comment]
Yes - jeg har selv bygget maxima.

Tiltet betyder at processen dør - og at dylib'en starter den igen (såvidt jeg husker).

Jeg lavede en logfil på disken som jeg skrev til forskellige steder fra (incl. trafik ind og ud af dylib).

Kan desværre ikke bidrage med så meget mere - solgte M1'eren igen.

**Comment by BrylleDK** [comment]
Ohøj I alvidende tech wizards. ;) 

Jeg er lykkedes med at compile maxima på M1 med SBCL, og arbejdede med at oprette den nye maxima.core jf. [https://github.com/Eduap-com/WordMat/blob/master/How%20to%20build%20WordMat.md](url). 

Men får
```
 "file_search1: solvereal not found in file_search_maxima,file_search_lisp.
 -- an error." 
```
Ved 
```
load(solvereal)$
```
Ved nogen af jer hvilken funktion det er, man forsøger kalde?   Har brugt en del tid på at søge mig til svar, men kan ikke finde noget om "solvereal" i maxima.

**Comment by soegaard** [comment]
Godt arbejde!

Filen "solvereal" er del af WordMat (ikke Maxima).

https://github.com/Eduap-com/WordMat/blob/master/Shared/Maxima-files/SolveReal%20Readme.md

Denne side beskriver, de ændringer der er i den Maxima, der kommer med WordMat, i forhold til den normale udgave.
Her er `Solvereal.mac`, `WordMatunitaddon.mac` og `Unit.mac` nævnt.

https://github.com/Eduap-com/WordMat/tree/master/Shared/Maxima-files

Nederst er der nævnt et par ændringer mere.

**Comment by BrylleDK** [comment]
Tak! :)

**Comment by BrylleDK** [comment]
@soegaard Jeg endte med at sidde fast i at få et script til at starte maxima, i forsøget på at få bygget maxima som standalone binary, og så jeg ikke haft tid til at sidde med det siden. 

Og med en beta på vej, tror jeg jeg smider håndklædet i ringen for denne omgang.

**Comment by mariussand** [comment]
Wordmat er nu tilgængeligt til m1 på deres hjemmeside som en beta :)

**Comment by Naimersejogjeppeersejer** [comment]
Hey, kommer direkte efter at have fulgt med i jeres process. 
Når jeg downloader progammet for jeg følgende fejl. 
**"WordMat.pkg" Kan ikke åbnes fordi det er fra en uidentificeret udvikler**
"MacOS ikke ikke bekræfte, at dette program er fri for malware"

Hvad kan jeg gøre?

**Comment by mariussand** [comment]
Hej, højreklik inden i finder på programmet og tryk åben

fre. 5. nov. 2021 kl. 08.37 skrev Naimersejogjeppeersejer <
***@***.***>:

**Comment by NAIMUXC** [comment]
Hey, hvor står de nye keybinds til ligning. 
Det plejer at være ALT - M, men det ser ikke ud til det virker og på hjemmesiden kan det heller ikke ses. 
MvH - Naim

**Comment by mariussand** [comment]
Det skulle gerne være det samme, er du sikker på at programmet er
installeret? - prøv evt. igen eller genstart pc’en.
fre. 5. nov. 2021 kl. 08.53 skrev NaimUXC112 ***@***.***>:

**Comment by Jona128m** [comment]
Har nogen fået held med beta-versionen af m1 WordMat?

**Comment by mariussand** [comment]
Jep, virker perfekt hos mig

tir. 9. nov. 2021 kl. 13.00 skrev Jona128m ***@***.***>:

**Comment by Jona128m** [comment]
Sjove at de ikke har opdateret deres beskrivelse af m1 MacBook support endnu... hmm de skriver: 

How about Mac-computers?
WordMat support Office 2011, 2016 and 2019 for Mac. Support for the 2011 version (1.04) has ended. There are some minor differences between the Windows and Mac version.
WordMat does not support the new Apple Silicon based Macs (M1). It is still unclear if a succesfull conversion can be made.

**Comment by mariussand** [comment]
Det har de på dansk, men ikke engelsk endnu.

tir. 9. nov. 2021 kl. 15.24 skrev Jona128m ***@***.***>:

**Comment by Jona128m** [comment]
Ved nogen om wordmat virker på Mac M1 montery version, fordi jeg ved at wordmat ikke virker med intel macs på montery versionen.

**Comment by BrylleDK** [comment]
Det gør det.
