### ISSUE TITLE
wordmat kan ikke starte maxima. prøvet med flere versioner Word 2016

### ISSUE THREAD

**Issue by Sattmann** [Eduap-com/WordMat#41]
jeg har akut problemer med at word ikke kan beregne noget. for en Error Code 2: wordmat kan ikke starte maximus med det samme når jeg prøver at beregne noget selv 2+2..

![wordmat maximus fejl](https://user-images.githubusercontent.com/12955906/118681758-1ebac700-b800-11eb-9fb7-b43c14ca6feb.png)

windows 10 Pro 64 bit

nogle der kender til denne fejl? jeg har prøvet at hente flere versioner

**Comment by tikh2004** [comment]
Er der en løsning på dette?

**Comment by Eduap-com** [comment]
Det kan være mange ting. Sandsynligvis Antivirus relateret eller DEP
