### ISSUE TITLE
WordMat hangs on new MacOS Monterey version and causes a memory leak

### ISSUE THREAD

**Issue by HLVM04** [Eduap-com/WordMat#42]
WordMat doesn't work on the new MacOS Monterey version. When I try to do any calculation, Word freezes and the ram usage explodes. Word is also stuck at 100% CPU usage. Seems like it's the "sbcl" process that causes this, which i believe is Maxima. It also seems like the Maxima version included in WordMat is from 2016 :/
Hopefully this is an easy fix, so I can get back to using this tool at school :)

**Comment by BrylleDK** [comment]
Might be a macOS bug: https://www.macrumors.com/2021/11/01/macos-monterey-memory-leak-user-reports/

**Comment by mortenegelund** [comment]
Got this issue on an Intel Mac.

**Comment by BrylleDK** [comment]
I have several students with this problem.  All intel Macs updated to Monterey.

**Comment by perfack** [comment]
Does the macOS Monterey version 12.1 have the same problem?

**Comment by HLVM04** [comment]
Can confirm the problem is exactly the same on macOS Monterey version 12.1 :(

**Comment by nielsle** [comment]
Some of my students have solved the problem by downgrading from macOs Monterey to Big Sur (or catalina). But this only works if you have access to big sur.
https://www.stellarinfo.com/blog/downgrade-macos-monterey-to-big-sur/
