### ISSUE TITLE
BUG in v 1.23 - 2 equations with 2 unknown 

### ISSUE THREAD

**Issue by BrylleDK** [Eduap-com/WordMat#43]
First of all: @Eduap-com, huge applause and thanks for the M1 update! 

Preparing for my math class I stumbled upon a bug when solving 2 equations with 2 unknown.

I get [x,y] ∈ Ø.  

[2ligninger-bug.docx](https://github.com/Eduap-com/WordMat/files/7476439/2ligninger-bug.docx)

**Comment by Eduap-com** [comment]
Problemet er rettet, og kommer med i næste version
