### ISSUE TITLE
Tilføj "kvadratrod(x)" i geogebra

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#44]
Kan det passe at wordmat tilføjer funktiioner til geogebra?

Hvis ja, så ville det være rart at tilføje en funktion  ved navn "kvadratrod"

Min elever har svært ved at huske at de skal skrive sqrt(x)

**Comment by Eduap-com** [comment]
Brug kvadratrodsregnet i ligningseditoren
