### ISSUE TITLE
Fejl ved løsning af ligning indeholdende bestemt integral (M1-Mac)

### ISSUE THREAD

**Issue by mathiasfugmann** [Eduap-com/WordMat#46]
WordMat til M1-Mac vil ikke løse vedhæftede ligning for den ukendte øvre grænse i integralet. WordMat til Intel-Mac kunne godt løse ligningen korrekt (testet på flere M1 og Intel Macs, alle M1'erne skrev, at ligningen ikke har løsninger).

[Integralligning.docx](https://github.com/Eduap-com/WordMat/files/7505911/Integralligning.docx)

**Comment by Eduap-com** [comment]
Problemet er løst
