### ISSUE TITLE
Læses issues?

### ISSUE THREAD

**Issue by soegaard** [Eduap-com/WordMat#49]
Hej, 

Jeg har kigget lidt på listen af Issues, men kan ikke se at  @Eduap-com 
har kommenteret - så nu er jeg kommet i tvivl om beskederne bliver læst.
Er der måske et problem med spam-filter eller lignende?

Mvh,
Jens Axel Søgaard

**Comment by Eduap-com** [comment]
Der kommer bare flere end jeg kan håndtere

tir. 1. feb. 2022 kl. 15.34 skrev Jens Axel Søgaard <
***@***.***>:

**Comment by soegaard** [comment]
Helt i orden!
