### ISSUE TITLE
Freeze in partial derivatives

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#5]
Hi Michael

Here is an other one. Wordmat freezes if I write spaces between "\partial/\partial x"  and "f(x,y)". It more or less looks like this, but look at the attached example file
~~~
f(x,y):=x^2+y^2
\partial/\partial x f(x,y)      //this works
\partial/\partial x     f(x,y)  //This causes wordmat to freeze
~~~
Kind regards

      Niels

[wordmat_freeze_partial_derivatives.docx](https://github.com/Eduap-com/WordMat/files/4303032/wordmat_freeze_partial_derivatives.docx)

**Comment by Eduap-com** [comment]
Fejlen er løst. Kommer med i næste opdatering
