### ISSUE TITLE
Wordmat giver umiddelbart forkert svar

### ISSUE THREAD

**Issue by KennethHald** [Eduap-com/WordMat#50]
Nogen der kender problemet? Se vide

https://user-images.githubusercontent.com/102579916/160555439-1e06dbc1-6718-452a-a4ce-b72d36b3a9e2.mp4

o

**Comment by nielsle** [comment]
Hvis du har en wordmat-fil der giver samme forkerte svar på flere forskellige computere med wordmat, så vil det måske hjælpe at uploade selve wordmat-filen på github. Ellers kan det være svært at genskabe fejlen. (Sammenlign med #18)

**Comment by Eduap-com** [comment]
Tak, Niels.
Ud fra videoen kan jeg se i ligningsmenuen at den er sat til Latex og ikke unicode. Det kan en masse problemer af denne art.
