### ISSUE TITLE
Grafer tegnes ikke på mac

### ISSUE THREAD

**Issue by HVN99** [Eduap-com/WordMat#51]
Jeg har en elev med en Intel mac opdateret til Monterey og wordmat 1.23. Hver gang han prøver at tegne en graf får han følgende fejlmeddelelse: "Billedfremviser kunne ikke åbne arkivet WordMatGraf.pdf, fordi det ikke findes". 
Vi har prøvet et fjerne og geninstallere både wordmat og officepakken uden held. 
Eleven er blind og bruger skærmlæser på sin mac.

**Comment by Eduap-com** [comment]
GnuPlot giver problemer og erstattes fremover af GeoGebra browser
