### ISSUE TITLE
GeoGebra som CAS moter i Windows

### ISSUE THREAD

**Issue by Soeren8** [Eduap-com/WordMat#52]
Hverken beregn eller løs lignig virker i Windows.

[WordMat 1.24.docx](https://github.com/Eduap-com/WordMat/files/8501489/WordMat.1.24.docx)
.

**Comment by Eduap-com** [comment]
Jeg er ikke i stand til at genskabe problemet. Det er afprøvet på mange computere.
Hvis andre spotter problemet og kan gennemskue hvad der specielt ved den maskine, så sig gerne til.
