### ISSUE TITLE
GeoGebra som CAS problem (har fundet løsning)

### ISSUE THREAD

**Issue by mathiasfugmann** [Eduap-com/WordMat#53]
Jeg er på en M1 Mac med nyeste version af Monterey (12.3.1). Jeg har downloadet WordMat version 1.24 og givet de nødvendige tilladelser i Safari til at skulle kunne bruge GeoGebra som CAS-motor.
Når jeg prøver at bruge GeoGebra som CAS-motor fås følgende fejl:
<img width="1135" alt="Skærmbillede 2022-04-17 kl  14 12 56" src="https://user-images.githubusercontent.com/93997454/163713789-5245d8f2-b6c4-49f8-b123-3b64efa05292.png">
Problemet er tilsyneladende manglende tilladelse til mappen "geogebra-math-apps", som ser således ud, når man prøver at tilgå den i Finder:
<img width="931" alt="Skærmbillede 2022-04-17 kl  14 10 55" src="https://user-images.githubusercontent.com/93997454/163713809-e0166666-ca33-4d9b-8f93-a784b26a8692.png">
Jeg har erstattet med mappen hentet direkte i GitHub, så det nu ser således ud i Finder:
<img width="931" alt="Skærmbillede 2022-04-17 kl  14 11 10" src="https://user-images.githubusercontent.com/93997454/163713865-22efd14a-05db-4366-976e-23fea6648fe1.png">
Herefter er der ingen problemer med at bruge GeoGebra som CAS-motor (en *fremragende* tilføjelse i øvrigt, stort cadeau!)

**Comment by Eduap-com** [comment]
Tak. Problemet er fundet og der er uploadet et nyt release.
