### ISSUE TITLE
Freeze when copying square root in wordmat

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#6]
If I use `\sqrt`  to write a square root in wordmat and try to copy it using ctrl-c, then wordmat freezes. This is what I write to create an "uncopyable equatiion".
~~~
<alt-m> \sqrt <space> (13) <alt-B>
~~~
I don't know if this is really a wordmat error, because I can sometimes reproduce the error if I uninstall wordmat and load the document again

* Create a document with an "uncopyable formula"
* Save the document
* Uninstall wordmat
* Load the document
* Try to copy the formula
* Freeze

Note that if I use the menu to create square-roots then I don't get a freeze, so I wonder if wordmat somehow adds a special character trat causes problems. Here is an example file

[sqrt_causes_freeze_when_copying_text.docx](https://github.com/Eduap-com/WordMat/files/4303143/sqrt_causes_freeze_when_copying_text.docx)

At some point when working with the document I got an asd-file and I think that I got a message that the document was damaged. I don't completely remember the details, but I attached the asd-file

[~WRA0000.asd.docx](https://github.com/Eduap-com/WordMat/files/4303144/WRA0000.asd.docx)

**Comment by Eduap-com** [comment]
This is an error in Word equations editor. I cannot reproduce it. Maybe Microsoft fixed it?
