### ISSUE TITLE
CAS motor GeoGebra giver forkert resultat ved løsning af ligningssystem

### ISSUE THREAD

**Issue by Rahbek3210** [Eduap-com/WordMat#62]
Anvendt:
- Windows
- WordMat version 1.24.2

Ved løsning af et ligningssystem (3 ligninger med 3 ubekendte) har jeg bemærket, at CAS motor Maxima og GeoGebra giver forskellige resultater. CAS motor GeoGebra giver et forkert resultat, hvilket virker meget spøjst, da ligningssystemet er forholdsvist simpelt.
Ligningssystemet er vist i vedhæftede word-dokument, hvor problemet også er undersøgt nærmere.

[RahbekWordMatBug1.docx](https://github.com/Eduap-com/WordMat/files/8877700/RahbekWordMatBug1.docx)

**Comment by Eduap-com** [comment]
Problemet er nu løst i koden, og kommer med i version 1.25

**Comment by Eduap-com** [comment]
1.25 er nu frigivet
