### ISSUE TITLE
Freeze when differentiating an undefined function

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#7]
I am sorry to spam you with issues, but here is another one
~~~
f(x)=x^2         // Note that I did not write :=
f'(2)                // wordmat freezes when I press alt-b here
~~~
Note that the function has not been defined, so wordmat cannot calculate f'(2), but ideally wordmat should not freeze

If I change the "=" in the first equation to ":=" then I get f'(2)=4 as expected
[freeze_when_differentiating_an_undefined_function.docx](https://github.com/Eduap-com/WordMat/files/4303441/freeze_when_differentiating_an_undefined_function.docx)

**Comment by Eduap-com** [comment]
Thanks for the issues. It will be a while until I can fix it though, but keep it coming.

**Comment by Eduap-com** [comment]
er nu løst.
