### ISSUE TITLE
2 equations will not be solved..

### ISSUE THREAD

**Issue by Leif29** [Eduap-com/WordMat#74]
I cant not get Wordmat 1.25 to solve 2 equations on my Mac (intel)

It only returns L= Ø even though equation is valid and solvable.

Only with same issues ??

BR

<img width="1001" alt="Skærmbillede 2022-08-19 kl  20 05 02" src="https://user-images.githubusercontent.com/111599627/185680320-53ccb7da-1cc5-4073-a07b-8bb941443d16.png">

**Comment by TorstenOrhoj** [comment]
No problems for me in Windows.
![image](https://user-images.githubusercontent.com/111779383/185975726-74c72e63-b54c-4177-bc71-f7c985b925b1.png)

**Comment by Eduap-com** [comment]
Problemet kan genskabes hvis enheder er slået til.
WordMat bliver markant dårligere til at løse ligninger med enheder slået til. Der er umiddelbart ikke så meget at gøre ved det.
Man bliver advaret om det
