### ISSUE TITLE
Wordmat flagged as Trojan - Microsoft Defender

### ISSUE THREAD

**Issue by Kinakaal** [Eduap-com/WordMat#78]
Wordmat is flagged as Trojan in Microsoft Defender when installed.

Windows 11.

![image](https://user-images.githubusercontent.com/112481974/187421107-dbd0330a-66b0-4a2d-b43e-c7c2c84bad2d.png)

**Comment by MasterSengir** [comment]
Yeah this is for current release of wordmat 1.25.2. Have seen this also being picked up by Avast antivirus. Hope to get a fix for this soon.

**Comment by haraldlander** [comment]
Yeah, I have the same problem since 2 days ago.

**Comment by Eduap-com** [comment]
Det er en falsk positiv. Det sker ind i mellem at antivirusprogrammer identificerer WordMat som virus, specielt lige efter en ny version er kommet ud. Over tid bliver virusdefinitionerne typisk opdateret.

**Comment by steenhjerrild** [comment]
Nu er den Trojanske hest der igen (ver. 1.29)
![image](https://github.com/Eduap-com/WordMat/assets/114024056/4fb8dbf9-5778-4b8b-b37a-aff7f4363b1f)

**Comment by CaMedEnHat** [comment]
Hver gang jeg beregner noget med mit wordmat så crasher word. Det skete efter det her:
![image](https://github.com/user-attachments/assets/7e017cac-ed4a-4d08-8166-1be310aef8aa)
