### ISSUE TITLE
berening fejler

### ISSUE THREAD

**Issue by madsmr40** [Eduap-com/WordMat#79]
jeg oplever at den ikke vil renge ud og at den bare står rigtig læge og så fejler den
hvis man så deakriver wordmat og prøver igen så kommer den med fejl

**Comment by Eduap-com** [comment]
Jeg har brug for mere information. 
**Windows eller Mac**
Hvis Mac er det så Intel eller M1/2?

**WordMat version**
Hvilken version? 

**Beskriv fejlen**
Klar og præcis beskrivelse af fejlen.

**Trin til genskabelse af fejlen**
Angiv *præcise* trin der kan genskabe fejlen
1. Gå til '...'
2. Klik  '....'
3. Scroll ned til '....'

**Forventet opførsel**
En klar og præcis beskrivelse af hvad du forventede skulle ske

**Dokument**
Tilføj dokument der kan frembringe fejlen. 

**Screenshots**
Send meget gerne screenshots der viser problemet.

**Comment by Eduap-com** [comment]
Ingen svar
