### ISSUE TITLE
f <space> (0) is interpreted as f*0=0

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#8]
In the following example I get the wrong result because I added a space betwen f and (0).
~~~
f(x):=2*x+1
f (0) = 0      // Note the space between f and (0)
f  (x) =f*x    // The problem is that wordmat interprets space as a multiplication
~~~
Ideally wordmat should discover that f has previously been defined to be a function, and therefore the space does not mean multiplication.
[space_between_f_and_(0).docx](https://github.com/Eduap-com/WordMat/files/4303488/space_between_f_and_.0.docx)

**Comment by nielsle** [comment]
I also tested partial derivatives and I get a somewhar  similar problem
[space_between_f_x'_and_(x;y).docx](https://github.com/Eduap-com/WordMat/files/4303552/space_between_f_x._and_.x.y.docx)

**Comment by perfack** [comment]
A similar "error" can be seen in the following:
       x(2x+1)
The first x is interpreted as a function name, and thus, the expression cannot be evaluated.
