### ISSUE TITLE
Crasher ved beregning

### ISSUE THREAD

**Issue by nikoruffet** [Eduap-com/WordMat#80]
Mit wordmat crasher hver gang jeg forsøger jeg trykker "beregn" eller "løs ligning". Jeg har forsøgt at genstarte, geninstallere både wordmat og office, men til intet held.

**Comment by mathiasfugmann** [comment]
Hvilket styresystem bruger du? Hvilken version af WordMat?

**Comment by nikoruffet** [comment]
Jeg bruger windows 10, og den nyeste version af wordmat (den på jeres hjemmeside).

**Comment by mijenner** [comment]
Prøv evt at downgrade til version 1.22 (afinstallere den du har nu inden). Jeg har selv problemer med 1.24 og 1.25.

**Comment by Eduap-com** [comment]
Det skyldes at Windows defender blokerer WordMat's forsøg på at checke for opdatering. Løsningen er at deaktivere automatisk opdatering under indstillinger | Avanceret.
Der er lavet ændringer i forsøget på at undgå dette problem, men Defenders virus definitioner ændres konstant, så problemet kan pludseligt opstå og forsvinde igen.
