### ISSUE TITLE
Skabeloner for issues

### ISSUE THREAD

**Issue by soegaard** [Eduap-com/WordMat#81]
Forslag: Lav en skabelon for nye issues.
Skabelonen skal minde om at inkludere information om operativsystem, version af Word og version af WordMat.
Et link til en FAQ er også en mulighed.

Se, hvordan man tilføjer en skabelon her:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Eduap-com** [comment]
Tak. Det var en god idé
