### ISSUE TITLE
Wordmat 1.24 og 1.25 virker ikke på Windows med Office 365

### ISSUE THREAD

**Issue by mijenner** [Eduap-com/WordMat#84]
Jeg skulle hjælpe elev som ikke kunne få Wordmat til at køre på hans windows pc. Den meldte noget om "Wordmat ikke korrekt installeret, prøv at disable anti-virus". Har prøvet uden at det hjalp - har lukket Word net fra "jobliste" - det hjalp heller ikke. Har set og afprøve alle hint på eduap.com - ingen af dem hjalp. 

Efter det forgæves forsøg på hjælp ville jeg lige opdatere egen installation - også på Windows - fra 1.22 til 1.25.2. 
Det gik ikke. Menuer mangler ikoner og tekst, tryk på tandhjulet virkede ikke. Short-cut alt+m virker ikke (og sikkert mange flere). 

Rul "tilbage" til 1.24 virkede heller ikke. 
Rul tilbage til 1.22 nu virker det igen. 

Jeg synes Wordmat er et lækkert system - når det virker.

Hvad kan jeg prøve næst?

**Comment by mijenner** [comment]
Faktisk er det Word 2016 som efterhånden er kraftigt linket ind i sharepoint og onedrive og måske også office 365.

**Comment by Eduap-com** [comment]
Det virker umiddelbart på de computere jeg har adgang til. Hvis du kan gennemskue hvorfor problemet opstår, så sig til.

**Comment by mijenner** [comment]
De sidste par dage har jeg haft 5 elever som har Wordmat på Windows som crasher. Downgrade til 1.22 har i alle 5 tilfælde afhjulpet problemet. 

Kan vi gøre noget for at give debug-eller-log-information tilbage hvis/når nogen vover at opgradere igen - og den crasher igen?  

Mvh Michael

**Comment by Eduap-com** [comment]
Det kan være relateret til om WordMat er sat til automatisk at opdatere. Når WordMat checker for opdatering kan antivirus og/eller Microsoft defender få Word til at crashe. 
Meld gerne tilbage om det virker at slå automatisk opdatering fra.

**Comment by mijenner** [comment]
Har netop prøvet hos elev som melder om crash. Det virker at slå automatisk opdatering fra!
