### ISSUE TITLE
Løsning af ligninger med normalfordeligs-integraler

### ISSUE THREAD

**Issue by Soeren8** [Eduap-com/WordMat#85]
Mac. Intel. Monterey. WordMat 1.25.1.
WordMat kan ikke beregne spredningen i normalfordelingen.
WordMat kan godt beregne middelværdien og WordMat kan beregne sandsynligheder.
[WordMat. Løsning af ligninger i normalfordelingen.docx](https://github.com/Eduap-com/WordMat/files/9640554/WordMat.Losning.af.ligninger.i.normalfordelingen.docx)

**Comment by nielsle** [comment]
Hmm...  Jeg har WordMat 1.25.1 med Maxima på windows, og min version af wordmat kan godt finde sigma
(Både med "numerisk", og "exact")

<img width="227" alt="image" src="https://user-images.githubusercontent.com/292118/192175642-3f337544-0a9a-41b1-99d1-4150cc853ec2.png">

**Comment by Soeren8** [comment]
Ja, det virker på Windows og på M1 Mac. Det virker ikke på Intel Mac, hverken med Maxima eller GeoGebra som CAS motor.

**Comment by Eduap-com** [comment]
For mig opstår fejlen både på M1 og intel. Word låser helt.
På Windows bliver man spurgt om fortegn på sigma, og hvis man definerer sigma til at være positiv virker det også på Mac.
Måske der kan gøres noget med noninteractive-mode i Maxima?

**Comment by Eduap-com** [comment]
Den metode der anvendes på Mac kan ikke bruges til at svare på spørgsmål, men nu låser Word på Mac ikke mere og man bliver guidet til at definere variablen.
