### ISSUE TITLE
Crasher ved Regression til Excel

### ISSUE THREAD

**Issue by Zetikan** [Eduap-com/WordMat#86]
Jeg har haft en kursist i dag som ikke kan lave en regression over til Excel.
Når hun forsøger, når WordMat at lave 3 blokke i tænke baren, åbne excel og derefter crasher både Word og Excel.
Almindelige beregninger virker fint.

Jeg har forsøgt at reinstaller og nedgrader WordMat. Samt en fuld reinstallation hvor jeg fjernede både Office pakken og WordMat og installerede dem igen. Men uden held.

Kursisten køre med Windows 11 22h2 og vi har forsøgt både med versionerne 1.25.2 og 1.25.1 i WordMat.
Jeg kiggede efter logs men kunne ikke finde om der bliver lavet nogle eller hvor de ligger.

**Comment by Eduap-com** [comment]
Hvad menes præcist med 'lave en regression over til Excel.'
Send det dokument som anvendes.

**Comment by Zetikan** [comment]
Det er et hvilket som helst dokument, alt lige fra en blankt A4 side til et større dokument, hvor man bare går op i feltet "Regression" og så vælger "Excel Regression" 
![regression](https://user-images.githubusercontent.com/70270027/199920278-a5ae238a-cf04-4f73-bbc2-f4a83e1799ce.png)

Jeg har dog ikke kursisten hos mig, men kan huske fejlen ret tydeligt.
Det er også personen som har problemet inde i Discussion gruppen med sag 94
https://github.com/Eduap-com/WordMat/discussions/94

Er der nogle ting som skal være tilgængelig på computeren (fx andre programmer eller features) som måske kan være skyld i de problemer som hun har? (Win 11)
Som jeg har skrevet tidligere så har vi forsøgt en hel del af de ting som jeg oplever er normale problemer, og løsnings muligheder. Men i dette tilfælde så har intet af hvad jeg har forsøgt virket.

**Comment by Eduap-com** [comment]
Det vil nok kræve en nærmere undersøgelse af computeren.
