### ISSUE TITLE
Wordmat can't multiply 

### ISSUE THREAD

**Issue by trglar** [Eduap-com/WordMat#87]
I can't multiply in Wordmat anymore. I have used it in several years and on different computers and I get the same error as below:

![error](https://user-images.githubusercontent.com/115095717/194095600-158e3062-37b7-424d-97aa-573d80796d86.png)

I have tried to:

-  repair office (Office 365)
- Uninstall and install Office again
- install both 1.24 and 1.25 versions of Wordmat
- Disable my antivirus (Defender)

But I still can't multiply.

I'm going to an Exam in 2 weeks - please reply fast

Thanks for your help

Emil

**Comment by trglar** [comment]
Det er alle dokumenter der fejler - både nye og gamle.

Jeg har dog prøvet at markere Unicode i Wordmat menuen og så indsætter den en prik som gange tegn og så virker det, men den kan ikke modtage * som regnetegn.

**Comment by soegaard** [comment]
Har du et konkret dokument, som andre kan prøve?

**Comment by trglar** [comment]
Vi har prøvet flere ens dokumenter på 3 forskellige dokumenter og det fejler på dem alle og vi har prøvet nye dokumenter på de samme pc'er og de fejler også. De 2 af PC'erne er med Windows 11 og Office 360 med nyeste opdatering og den sidste er Windows 10 men med samme version af Office 365. PC'erne med Windows 11 er med licens fra folkeskolen og Windows 10 maskinen er med en Bus. Premium licens til O365.

**Comment by soegaard** [comment]
Prøv evt. version 1.23 i stedet.

https://github.com/Eduap-com/WordMat/issues/84

**Comment by soegaard** [comment]
http://www.eduap.com/download-wordmat/

**Comment by Eduap-com** [comment]
Jeg har ikke set denne fejl før. Det kan være at der er sat noget forkert matematisk autokorrektur.
Sørg også for at der er valgt unicode i ligningsmenuen og ikke Latex:
![image](https://user-images.githubusercontent.com/27739684/199718304-ba9e35bc-eeca-411d-ae0a-c4d3ac660278.png)
