### ISSUE TITLE
Autocorrect "WordMat" to 68^2+72^2-2·68·72·cos⁡(48)≈3255,873

### ISSUE THREAD

**Issue by ankr2808** [Eduap-com/WordMat#88]
Hej Mikael
Når jeg skriver "WordMat" + Enter, erstattes teksten af "68^2+72^2-2·68·72·cos⁡(48)≈3255,873". Jeg har kigget i autokorrektur og matematisk autokorrektur, men jeg kan ikke finde det der. Jeg mener at det må være noget der ligger i WordMat, da det sker på flere computere.
Vh Anders

**Comment by Eduap-com** [comment]
Jeg kan ikke genskabe problemet. Det ligger ikke i koden.
Det kan muligvis være relateret til WordMark der arbejder med tastegenveje.
