### ISSUE TITLE
Feed back on the binomial test excel sheet

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#9]
I think that there is a small mistake in the formula for confidence interval for p in the binomial test excel sheet

I assume that 
* "forventet p" (cell C3) is the value of p that is mentioned in the null hypothesis (H: p=p0)
* "observed p" (cell C4) is estimated from the number of succeses in the sample ( \hat p = r/N)

If that is true then I think that you should use  \hat p = r/N (cell C4) to when calculating the confidence interval for p. The idea is that you use the number of observed successes in the sample to construct a confidence interval. Once this interval is constructed, then you can test a null hypothesis H0:´p=p0, by examining if po is contained in the confidence interval. In other words the confidence interval is independent of constant p0 from the null hupothesis,  Here is a video.

https://www.youtube.com/watch?v=-2KRNFk8oEA

I realize that wordmat is also doing a meaningful calculation, but I don't think that it is consistent with formula for "confidence interval for p" in the official curriculum.

It is probably not a good idea to change this shortly before the exams that may or may not take place this summer....

PS: The observed number of successes use usually called r or \hat x.  \mu usually denotes the true mean. (Edited)

**Comment by Eduap-com** [comment]
Thanks for the explicit description.
I changed the notation to use \hat p and \hat x,
and introduced a second confidence interval for \hat p.
Could you check it out before release? Download the new excel file under Windows/excelfiles

**Comment by nielsle** [comment]
Det ser godt ud, men jeg har en enkelt kommentar.

Teknisk set, så tror jeg ikke at man kalder celle j20 for et "konfidensinterval", så jeg er lidt bange for at navnet kan forvirre eleverne, så måske kan man give den et andet navn. 

Jeg ved ikke hvad dette interval hedder i litteraturen, men måske kunne man kalde den for for "Acceptmængde for p\hat" eller "Acceptmængde for andel"

Så alt i alt kunne wordmat måske skrive tre intervaller
~~~
Acceptmængde  {0,.. 3}                               <- {k1, ...K2}
Acceptmængde for andel: [0,0; 0,3]          <- omdøbt fra kondidensinterval for p\hat
Konfidensinterval for p:  #værdi                <- Ikke omdøbt
~~~

Hvis jeg indtaster n=10 og p=0, så bliver "acceptmængde for andel [0; 0,308]", og jeg kan ikke helt overskue hvorfor. Jeg synes at svaret burde være [0; 0]

**Comment by Eduap-com** [comment]
Der er ændret en del i arket nu med v. 1.24.
Jeg håber det er landet et fornuftigt sted.
