### ISSUE TITLE
Menuen Funktion > Lineær 

### ISSUE THREAD

**Issue by ankr2808** [Eduap-com/WordMat#90]
Kunne man til menuen Funktioner > Lineær tilføje to linjer med

    f(x) = a x +b     Lineær funktion
    b = y_1 - a x_1    Begyndelsesværdi

til menuen Funktioner > Polynomisk

    x = (-b±√(b^2-4ac))/2a        Rødder
    d=b^2-4·a·c

og til menuen inf

    (f(x) - f(x_0)) / (x - x_0)       Differenskvotient

**Comment by Eduap-com** [comment]
Jeg vil hellere minimere antallet af formler, til de mest nødvendige.
Ved de to første kan man bruge ligningsløseren. Ligningerne er primært til uden hjælpemidler.
Den sidste tror jeg ikke vil blive brugt ret meget, da den ikke vil indgå til skriftlig eksamen
