### ISSUE TITLE
ShellExecuteEx Failed; code error 8235

### ISSUE THREAD

**Issue by mkkristiansen** [Eduap-com/WordMat#92]
Hej

Jeg får følgende fejl når jeg forsøger at installere WordMat:

![image](https://user-images.githubusercontent.com/115614127/195268918-6acf3a82-5107-42b1-b252-3f5c8c0adbda.png)

Jeg har forsøgt med både 1.25.2 & 1.25.1 uden held. Dog kan jeg fint installere 1.24.2
Jeg har forsøgt at kører .exe filen med administrator rettigheder og disabled UAC.
Jeg har ikke mulighed for at ændre i gpedit.

**Comment by Eduap-com** [comment]
Fejlen er blevet løst. Bare download 1.25.2 igen
