### ISSUE TITLE
WordMat can't solve (x+1)*e^-x=0

### ISSUE THREAD

**Issue by Soeren8** [Eduap-com/WordMat#95]
Windows with WordMat 1.25.2
[Ligning.docx](https://github.com/Eduap-com/WordMat/files/9853979/Ligning.docx)

**Comment by MikkelRuben** [comment]
Maxima numerisk løsning var super god før, så håber at fejlen bliver rettet.

**Comment by Eduap-com** [comment]
Numerisk løsning vil aldrig blive perfekt. Der er et tradeoff mellem at finde for få eller for mange.
