### ISSUE TITLE
Mac: Excel regression fejler ved åbning af Graphs1 mappe

### ISSUE THREAD

**Issue by ChrisHuelle** [Eduap-com/WordMat#96]
Når en elev prøver at starte Excel regression i WordMat, så starter Excel, og dialogboksen med tilladelse af makroer kommer op flere gange, hvor man vælger "Aktiver makroer", indtil WordMat til sidst sætter tabelområdet ind som et billede i Word dokumentet.
Umiddelbart ser det ud, som om WordMat ikke får lov til at generere Excel fanerne.

Jeg kan ikke selv genskabe problemet. Jeg har kun Mac OS 13.0 til forskel.

Er der en løsningsmulighed ?

Mac OS version: 12.6
Word version 16.66.1
Excel version 16.66.1
WordMat version: 1.25.1 (Intel)

**Comment by Eduap-com** [comment]
Det vil nok kræve en undersøgelse af den konkrete computer.
