### ISSUE TITLE
Komando  afbrudt efter 5 sekunder

### ISSUE THREAD

**Issue by 1827f** [Eduap-com/WordMat#97]
Hvordan løser man problemet når WordMat fortæller at kommandoen er afbrudt efter 5 sekunder?

**Comment by Eduap-com** [comment]
Jeg har brug for langt mere information omkring dette problem

**Comment by 1827f** [comment]
Hej
Jeg har kun det vedhæftede billede. Meddelelsen kommer hver gang at der laves en beregning.

[Et billede, der indeholder tekst, monitor  Automatisk genereret beskrivelse]

Fejlen fremkommer på en Mac med Monteray med nyeste version af WordMat.

Med venlig hilsen
Dennis Nielsen
Favrskov Gymnasium

Fra: Eduap-com ***@***.***>
Dato: torsdag, 3. november 2022 kl. 13.23
Til: Eduap-com/WordMat ***@***.***>
Cc: Dennis Nielsen ***@***.***>, Author ***@***.***>
Emne: Re: [Eduap-com/WordMat] Komando afbrudt efter 5 sekunder (Issue #97)

Jeg har brug for langt mere information omkring dette problem

**Comment by User7913** [comment]
Blev dette problem løst ?

**Comment by Eduap-com** [comment]
Jeg kan ikke se billedet, der må være gået noget galt under indsættelsen.
