### ISSUE TITLE
Får en fejl når jeg forsøger at åbne formelsamlingerne i Wordmat

### ISSUE THREAD

**Issue by kastoff** [Eduap-com/WordMat#99]
Jeg får fejl hver gang jeg forsøger at åbne en af de tre formelsamlinger. Der står blot, at der er sket en fejl i forsøget på at åbne Matformler.docx.  Nogen der kan hjælpe med en løsning? Tak :-)

**Comment by Eduap-com** [comment]
Windows eller mac?

**Comment by kastoff** [comment]
Windows 11 - Word 2016

**Comment by Eduap-com** [comment]
Det vil nok kræve handson på den enkelte maskine, da det er et sjældent problem
